### ISSUE TITLE
Need FAQ on Ingress support for mTLS

### ISSUE THREAD

**Issue by andraxylia** [istio/istio.github.io#1000]
From Slack:

"I think in order for external service to ingress mTLS to work, the story would be similar to the internal mTLS. Both the external caller and the ingress would need a workload cert issued by Istio CA, and both of them have to trust the Istio CA cert."
...
"how do we tell the ingress controller to only allow connections which perform the mtls though?  is there a flag?"

**Comment by myidpt** [comment]
By configuring ingress in the following way, the ingress will only allow mTLS traffic.
https://istio.io/docs/tasks/traffic-management/ingress.html#configuring-secure-ingress-https
More info on securing K8s ingress:
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

**Comment by myidpt** [comment]
I can add a FAQ item about this.
