### ISSUE TITLE
Manual sidecar injection instructions are not clear

### ISSUE THREAD

**Issue by wmwong** [istio/istio.github.io#1005]
Doc: https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection

It is not clear that this section describes 2 ways of performing manual sidecar injection and then a verification step.

The commands look like they should just be run in order:
1. Apply sleep.yaml
2. Generate yamls.
3. Generate sleep-injected.yaml
4. Apply sleep-injected.yaml
5. Verify

However, it should be made clear that the commands are actually structured as such:
Command 1 is one way.
Command 2-4 is another way.
Command 5 is verification for both ways.

**Comment by sdake** [comment]
I tend to agree this has tripped people up in the past including me.  Not quite sure how to fix it in the documentation.  Note in the implementation, sidecar injection is being automated, so this doc will likely change rapidly prior to 0.8 of Istio.  It makes more sense to me to spend the time tidying this document once that automated sidecar injection work completes (e.g. all of the manual steps are in the process of being automated).

**Comment by BusCommander** [comment]
Also the command for kube-inject does not work (at least on windows) 
`kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml)`

My suggestions would be something like 
`istioctl kube-inject -f samples/sleep/sleep.yaml | kubectl apply -f -`
which i find a little clearer to read and should work on every machine

**Comment by geeknoid** [comment]
@ayj Could you please make sure this all makes sense and works?
