### ISSUE TITLE
Document JWT auth feature implemented in Envoy proxy.

### ISSUE THREAD

**Issue by qiwzhang** [istio/istio.github.io#1019]
JWT auth feature for Envoy proxy is implemented with some limited features.  Need a document to describe its usage.

Here is the detail:

we have is the README and code in this folder.
https://github.com/istio/proxy/tree/master/src/envoy/auth

  and proto definition here.

https://github.com/istio/api/blob/master/mixer/v1/config/client/auth.proto#L43

There are two ways to use it
1) Not via Istio,  directly use Envoy.   The README describes that.
2) Via Istio,  then they need to use CRD,

**Comment by ayj** [comment]
Similar https://github.com/istio/istio.github.io/issues/877

**Comment by ldemailly** [comment]
I'd focus on 2. - this being istio and all :-)

**Comment by wattli** [comment]
It's in 0.8 doc already: https://preliminary.istio.io/docs/tasks/security/authn-policy.html#setup-end-user-authentication
