### ISSUE TITLE
selecting 0.5 reloads the page as same 0.6 preliminary

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#1034]

**Comment by ldemailly** [comment]
ping ? it's quite odd to not be able to select the 0.5 release which has been out for weeks
also 0.6 is out now as well and needs release notes

**Comment by ldemailly** [comment]
part of the fix in #1048

**Comment by ldemailly** [comment]
@geeknoid ping - how do users get to 0.5.1 docs ?

**Comment by ldemailly** [comment]
guessing #1052 is part of the solution (it'd be great to link PRs to issues...) but still not working

can you just make 0.5 go to 0.5 archive/why not ? (how is it different from 0.4, 0.3...)

**Comment by geeknoid** [comment]
​The solution is the DNS changes I emailed you about on Friday. Once these
changes are in place, then I can get everything working as expected.
​

**Comment by geeknoid** [comment]
Got it working prior to the DNS changes.

**Comment by ldemailly** [comment]
thanks!
so we just need 0.7pre now ?

**Comment by geeknoid** [comment]
Yes, that's the part that needs the DNS work.
