### ISSUE TITLE
Moving service from k8s to Istio

### ISSUE THREAD

**Issue by linsun** [istio/istio.github.io#1046]
I spent a day to debug a problem encountered when moving a simple service from k8s to Istio.  It turned out I'm not using http as the name of the service port.

@frankbu kindly pointed to me doc:  https://archive.istio.io/v0.1/docs/tasks/integrating-services-into-istio

We need to move (and validate/update as needed) the doc back to master as it is an important scenario.

**Comment by frankbu** [comment]
documented here: https://istio.io/docs/setup/kubernetes/sidecar-injection/#pod-spec-requirements and in troubleshooting: https://istio.io/help/troubleshooting/#route-rules-have-no-effect-on-my-application
