### ISSUE TITLE
Missing helpful informations in "Upgrading Istio" page

### ISSUE THREAD

**Issue by scraly** [istio/istio.github.io#1071]
The page https://istio.io/docs/guides/upgrading-istio.html is not very helpful for the moment ;-).

![upgrading_istio](https://user-images.githubusercontent.com/2543381/37277144-282c1fca-25e4-11e8-9d0f-423858ed7192.png)

**Comment by jsenon** [comment]
AFAIK, we prefer to uninstall and reinstall istio from scratch. Be sure to restart your POD that have envoy attached. @geeknoid @ldemailly @ayj correct me if i'm wrong.

**Comment by ldemailly** [comment]
@jsenon it's not a practical solution for real installations. @yusuoh is working on upgrade path
(and we are starting to test backward compatibility too in CI, so does @costinm before each release)

**Comment by yusuoh** [comment]
We have a draft document describing the upgrade process. I will update the web page once it got approved.
https://docs.google.com/document/d/1oxrlCgL7R0b_r4aIIFyBne2IxN1Lof3edo9YPy6h2Yk/edit

**Comment by scraly** [comment]
Thanks guys 😉.
I've read the document @yusuoh, seems to be very complete ^^, just one typo i've found:

UPDATED_DEPLOTMENT_WITH_SIDECAR_YAML

->

UPDATED_DEPLOYMENT_WITH_SIDECAR_YAML

Thanks.

**Comment by yusuoh** [comment]
Thanks for pointing it out. Fixed the typo.

**Comment by yusuoh** [comment]
Here is the updated doc:
https://istio.io/docs/setup/kubernetes/upgrading-istio.html
