### ISSUE TITLE
Add a copy button to <code> sections

### ISSUE THREAD

**Issue by ZackButcher** [istio/istio.github.io#108]
Many of our docs' `<code>` sections are commands we expect the user to copy from the page and paste into their terminal. It'd be nice if we had a small "copy code section to clipboard" button on all of our `<code>` sections. Similar to GitHub's "Clone or download" dialogue:

![image](https://cloud.githubusercontent.com/assets/1923135/25688677/1a084bca-3036-11e7-9ea8-6a6c4bb46fc1.png)

**Comment by geeknoid** [comment]
Done.
