### ISSUE TITLE
Enable checkin bots

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#1088]
We need to enable the bots to enforce the OWNERS file discipline in the istio.github.io repo in order to make sure the right people are involved in reviewing our docs.

Thanks.

cc @frankbu

**Comment by hklai** [comment]
istio.github.io is another good candidate to enable Tide.

**Comment by sebastienvas** [comment]
Tide does not support required check now, it needs all checks to pass. I am working on it.
