### ISSUE TITLE
Update Helm docs

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#1113]
https://istio.io/docs/setup/kubernetes/helm.html probably needs some updates. In particular, it states in bright red letters that helm support is currently broken.

**Comment by sdake** [comment]
Totally agree; I have been waiting for dust to settle on the `helm template` work before reworking this page.

Current task list:
Use syntax similar to my rework on the Ansible install docs in https://github.com/istio/istio.github.io/pull/1130
- [X] Define bottom pin on Istio Helm version support - PR: https://github.com/istio/istio.github.io/pull/1125
- [X] Refine Header and overview section and rename the various installs in ${tool}-install.md - PR https://github.com/istio/istio.github.io/pull/1086
- [ ] Run helm-install.md through spell | sort | uniq and yaml linter
- [ ] Make helm table options match existing implementation.
- [ ] Add customization examples as are used in the Ansible documentation submitted originally by @geoand 

Anyone is welcome to assist with a task - just respond on this issue tracker.
