### ISSUE TITLE
Issue with TOC (in _docs/setup/kubernetes/sidecar-injection.md and elsewhere)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#1116]
https://istio.io/docs/setup/kubernetes/sidecar-injection.html

I wanted to hyperlink the "Pod Spec Requirements" section but I can't

the toc is missing the top level entries

![screen shot 2018-03-28 at 4 45 14 pm](https://user-images.githubusercontent.com/3664595/38062224-a83383d2-32a7-11e8-9e2c-18716b7dde42.png)

any idea why @geeknoid  ?

( a work around I suppose is to add 1 # to every # xxx but is that an issue site wide?)

**Comment by geeknoid** [comment]
The problem is in the doc. We only use h2..h6 in .md files, h1 is used by the web site infrastructure itself to put the title at the top of the page.

I'll patch up the doc.

**Comment by ldemailly** [comment]
probably should document that h1 is illegal (and make rake test or grep for it because my guess is it's likely to be a problem in other pages)

**Comment by ldemailly** [comment]
it's hard to grep with all the snippet with comments - it does look that's the only page unless I missed something

**Comment by ldemailly** [comment]
Injection is still not in the TOC 

https://github.com/istio/istio.github.io/pull/1117#issuecomment-377079399

**Comment by geeknoid** [comment]
This is fixed on preliminary.istio.io, so it'll be pushed to istio.io as
soon as 0.7 is launched.


On Fri, Mar 30, 2018 at 11:12 AM, Laurent Demailly <notifications@github.com

**Comment by ldemailly** [comment]
again, it is not

![screen shot 2018-03-30 at 11 17 57 am](https://user-images.githubusercontent.com/3664595/38148654-39f342c0-340c-11e8-856c-325492b4bed4.png)

**Comment by ldemailly** [comment]
fixed in #1126
