### ISSUE TITLE
add MD linter to jekyll container

### ISSUE THREAD

**Issue by sdake** [istio/istio.github.io#1131]
I use the MD linter here:
http://dlaa.me/markdownlint/

Which is based upon this upstream:
https://github.com/markdownlint/markdownlint

The web page works pretty well but increases the dev cycle time of documentation as lint errors are resolved.  It would be nice if the jekyll container spit out any markdown errors (some MD lint rules would need to be excluded such as table heading checking).

Another more ambitious goal would be to make the markdown linter gate.

**Comment by geeknoid** [comment]
Should I close this then, or do you think we need more?

**Comment by sdake** [comment]
I can't think of additional work.  I'll close.
