### ISSUE TITLE
istio.github.io repo sometimes blocks on changes to references to istio.io

### ISSUE THREAD

**Issue by sdake** [istio/istio.github.io#1135]
There are a lot of links to istio/istio (edited: was istio/istio.io) in the istio.github.io repository.  Would be helpful to have a cross-repo gate in istio/istio that was voting (i.e. required).  I don't know if this is viable with circleci, but would help prevent blockages on the documentation repository.

Chees
-steve

**Comment by geeknoid** [comment]
Could you clarify? I can't make out what you're asking for.

Thanks.

**Comment by sdake** [comment]
Sure - this may be a minor issue and not worth  the trouble however. :)

If istio/istio repository is changed and a file in istio.github.io references it, the LinkChecker will fail, temporarily blocking all commits to the documentation repository until istio.github.io is modified to address the changed links in istio/istio.  The proposal is to add a check to istio/istio that runs the linkchecker against the current state of master for istio.github.io to prevent oncall situations like:

https://github.com/istio/istio.github.io/pull/1132

This is called cross-repo gating.

Cheers
-steve

**Comment by geeknoid** [comment]
Issue moved to [istio/istio #6269](https://github.com/istio/istio/issues/6269) via [**ZenHub**](https://www.zenhub.com/)
