### ISSUE TITLE
Add example to support enable TLS (not mTLS) for a service

### ISSUE THREAD

**Issue by wattli** [istio/istio.github.io#1152]

**Comment by linsun** [comment]
Thanks Tao!

**Comment by diemtvu** [comment]
For early adopter, here is an example authentication policy that can be used to setup hybrid mTLS/TLS on a service. A details docs for authentication policy is WIP

```bash
cat << EOF | istioctl create -f -
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "hybrid-mtls"
spec:
  targets:
  - name: httpbin
  peers:
  - mtls:
      allowTls: true
EOF
```

**Comment by linsun** [comment]
@wattli does this apply to external service too?  see https://github.com/istio/istio/issues/4764. cc @elevran

**Comment by diemtvu** [comment]
Authn policy is currently focus on services inside the mesh. While it can be used to 'disable' mTLS for external services, it may not feasible to config TLS/mTLS for external services (yet), as Istio doesn't have way to enforce on the server side.

**Comment by diemtvu** [comment]
@wattli, this option is removed; we will support only http/mTLS (multiplex) or mTLS only. Can we close this issue

**Comment by wattli** [comment]
Yes, close it for now, this is not gonna happen in 1.0
