### ISSUE TITLE
Quick Start Kubernetes 

### ISSUE THREAD

**Issue by jsenon** [istio/istio.github.io#1156]
Hi,

In Quick start Kubernetes documentation path in `Installation steps` section 3 is not correct, I would like to modify it but it's automatically replace by git branch name. So we have `cd istio-0.7` but Its `cd istio-0.7.1`. Appreciate If somebody explain me how to correct this (create branch release-0.7.1 seems not the correct way to do)

**Comment by sdake** [comment]
@jsenon good catch with this problem.  I believe the documentation is suitable as is, but it is a little confusing and will need a resolution prior to 1.0.z.  I'm not really sure the best way to solve this problem.

A branch from the 0.7 branched hash would solve this problem, however, I'm not sure we want to get into branching z streams for documentation prior to 1.0.z.

One solution (that may be a little over-the-top):

* submit a hardcode of the version to master
* cherrypick patch to 0.7 branch
* revert the hardcode of the version to master

This keeps a "master-first" approach - which is a best practice without the problems of branching a 0.7.1.  This may also be too much.

Given that the instructions state:

https://istio.io/docs/setup/kubernetes/quick-start.html#installation-steps
(step 3)
```
Change directory to istio package. For example, if the package is istio-0.7
cd istio-0.7
```

A third option would be to just ignore the problem and expect the operator to read the conditional "for example, if"

Perhaps @geeknoid has a better solution in mind than the 3 choices above.

Cheers
-steve

**Comment by geeknoid** [comment]
We definitely don't want to branch docs on patch versions, that'd be too much.

I think the text is clear enough as-is, it's just stating an example.

**Comment by geeknoid** [comment]
As I said, I think it's OK.
