### ISSUE TITLE
Document port naming in Istio

### ISSUE THREAD

**Issue by ZackButcher** [istio/istio.github.io#1178]
We require port names be prefixed by protocol to be able to take advantage of protocol level knowledge (e.g. to be able to do L7 request matching vs only being able to do L4 request matching). There are a few references to port naming scattered across docs (e.g. in tasks [1](https://istio.io/docs/setup/kubernetes/sidecar-injection.html#pod-spec-requirements), [2](https://istio.io/docs/tasks/traffic-management-v1alpha3/ingress.html#configuring-ingress-using-a-kubernetes-ingress-resource), and [in new reference docs](https://istio.io/docs/reference/config/istio.networking.v1alpha3.html#Destination)), but I could not find a document describing our requirements and how they map to protocols at runtime.

We should clearly document this as it's a common stumbling block for new users.

@rshriram - we could just not do this if in 0.9 we remove v1alpha1 APIs and totally remove port names in v1alpha3 API surface (in favor of number+protocol).

**Comment by jsenon** [comment]
Do you want to add it on [help](https://preliminary.istio.io/help/faq/) page?

**Comment by jsenon** [comment]
@ZackButcher I propose #1393
