### ISSUE TITLE
Question about the fault injection description.

### ISSUE THREAD

**Issue by wldandan** [istio/istio.github.io#1213]
In the documentation, there is a phase described "we will inject a 7s delay between the reviews:v2 and ratings microservices, for user “jason”. **Since the reviews:v2 service has a 10s** timeout for its calls to the ratings service, we expect the end-to-end flow to continue without any errors"
I am not clear where can get the more information about "Since the reviews:v2 service has a 10s? Is related to the 7s injected?"
Thanks a lot.

**Comment by ymesika** [comment]
The 10s timeout is hardcoded within the [reviews microservice implementation](https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java).
Line 89: `String timeout = star_color.equals("black") ? "10000" : "2500";`

**Comment by ymesika** [comment]
Hopefully it's better explained now in #1266 

/close
