### ISSUE TITLE
Document known 0.8 issues

### ISSUE THREAD

**Issue by linsun** [istio/istio.github.io#1225]
Gateway with virtual service to headerless service won't work.   https://github.com/istio/istio/issues/5005

Istio-ingress won't have any route rule support.  User must move to the new Gateway and new route rule to get this path working.  https://github.com/istio/issues/issues/296

**Comment by geeknoid** [comment]
Please add known issues to _about/notes/0.8.md

Thanks.

**Comment by linsun** [comment]
close out, think #4911 is no longer an issue.
