### ISSUE TITLE
Issue with _docs/guides/bookinfo.md

### ISSUE THREAD

**Issue by apichick** [istio/istio.github.io#1230]
This diagram is very confusing because it only shows the envoy sidecar proxy for the productpage service.

https://istio.io/docs/guides/img/bookinfo/withistio.svg

Shouldn't it be also shown for the rest of the services?

**Comment by frankbu** [comment]
The envoy label on productpage is pointing to the black box as an example, meaning all the black boxes (sidecars) in the diagram are envoys. We don't want to clutter the diagram anymore.
