### ISSUE TITLE
the v1alpha3 blog post clarifications

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio.github.io#1236]
Several points regarding the blog post https://preliminary.istio.io/blog/2018/v1alpha3-routing.html are confusing for me:

1. > Such entries are treated just like all other internal services, unlike external ones where Istio’s mTLS authentication is disabled and policy enforcement is performed on the client-side as opposed to server-side.

I see that external ones are those with location Mesh.External - https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html#ServiceEntry.Location. Maybe the difference should explained by two sentences, something like: _ServiceEntries can be of two types: mesh-internal and mesh-external. Mesh-internal Service Entries are like all other internal services. Mesh-external Service Entries represent services external to the mesh, for them  mTLS authentication is disabled and policy enforcement is performed on the client-side, and not on the server-side as for the internal services._

2. > Secure HTTP services (automatic TLS upgrade) can now be accessed using standard https (e.g., https://secureservice.com/ instead of http://secureservice.com:443/.

The example for HTTPS https://preliminary.istio.io/docs/tasks/traffic-management-v1alpha3/egress.html#make-requests-to-the-external-services still shows calling `http://google.com:443`.

3. > The resolution mode for the endpoints is now configurable (PASSTHROUGH, STATIC, or DNS).

According to 
https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html#ServiceEntry.Resolution, the resolution mode values are NONE, STATIC and DNS, not PASSTHROUGH.

**Comment by frankbu** [comment]
@vadimeisenbergibm thanks for the feedback. Fixes in https://github.com/istio/istio.github.io/pull/1238
