### ISSUE TITLE
It seems to be typo.

### ISSUE THREAD

**Issue by YunSangJun** [istio/istio.github.io#1245]
It seems to be typo on the following page.
https://github.com/istio/istio.github.io/blob/8e271cc89653a70dab088daee2fc5b8268be34d4/_docs/tasks/traffic-management-v1alpha3/fault-injection.md

In `Fault injection using HTTP Abort -> 3.Observe application behavior` section

I suppose that `ratings v1` is right than `ratings v2`.

Login as user “jason”. If the rule propagated successfully to all pods, you should see the page load immediately with the “product ratings not available” message. Logout from user “jason” and you should see the <b>ratings v2</b> show up successfully on the productpage web page.

**Comment by frankbu** [comment]
Fixed in https://github.com/istio/istio/pull/5471

**Comment by YunSangJun** [comment]
@frankbu 
In the guide page which is prerequisite of [fault-injection](https://istio.io/docs/tasks/traffic-management/fault-injection.html) tutorial, only `ratings: v1` service was deployed. 
https://istio.io/docs/guides/bookinfo.html#deploying-the-application

Therefore, i suppose that the route to `ratings: v2` will not be valid.
https://istio.io/docs/tasks/traffic-management/fault-injection.html
Login as user “jason”. If the rule propagated successfully to all pods, you should see the page load immediately with the “product ratings not available” message. Logout from user “jason” and you should see the <b>ratings v2</b> show up successfully on the productpage web page.

So i think that it had better modify from `ratings v2` to `ratings v1` on [fault-injection](https://istio.io/docs/tasks/traffic-management/fault-injection.html) tutorial.
https://github.com/istio/istio.github.io/pull/1246

**Comment by frankbu** [comment]
The bookinfo guide deploys ALL versions of the `reviews` service. This task needs to work with `reviews:v2` because it's testing faults on the `ratings` service which is not called by `reviews:v1`.

**Comment by frankbu** [comment]
Oh sorry, you are right @YunSangJun. I was confused because I thought we were configuring the version of the `reviews` service, but it's `ratings:v2` that this is about. I will revert the change I made to the yaml files.

The actual fix in the doc is to say that you should see "reviews v2", not "ratings v2". That's what threw me off. I'll fix the doc as well.

Thanks for your help @YunSangJun.

**Comment by frankbu** [comment]
Fixed by removing any mention of ratings service version, since that's not relevant.
