### ISSUE TITLE
Some missing clarifications around Egress rules

### ISSUE THREAD

**Issue by ahmetb** [istio/istio.github.io#1256]
I just read this section: https://istio.io/docs/concepts/traffic-management/rules-configuration.html#egress-rules

1. It's unclear what happens if I drop `spec.ports[]` field. (does it allow all ports? please clarify in docs.) (Is it allowed to omit this field at all?)

2. It looks like in this case Istio actually requires changes to your application code if you're calling external HTTPS services. (you HAVE TO send requests over `http://` on port :443) if the egress external service is serving on `https://`.

   This sounds contradictory to "without any changes to the deployed application code"  narrative listed at https://istio.io/docs/concepts/what-is-istio/goals.html If this is indeed the case, it might be better to either stick to the _"promise"_ or have a list where this promise doesn't apply.

**Comment by frankbu** [comment]
EgressRule has been replaced by ServiceEntry, which addresses these issues. 

https://preliminary.istio.io/docs/concepts/traffic-management/#service-entries
https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry
https://preliminary.istio.io/docs/tasks/traffic-management/egress/
