### ISSUE TITLE
Issue with _docs/reference/config/adapters/index.md

### ISSUE THREAD

**Issue by mabushey** [istio/istio.github.io#1261]
Bottom link for `Adapter Developer’s Guide` gives a 404.

**Comment by ymesika** [comment]
Works for me.
Current [prelim doc](https://preliminary.istio.io/docs/reference/config/adapters/) links to [alive guide](https://github.com/istio/istio/wiki/Mixer-Adapter-Dev-Guide).

**Comment by geeknoid** [comment]
We moved the guide a few weeks back, but haven't yet refreshed istio.io accordingly. The fix will come in when we update istio.io for 0.8.
