### ISSUE TITLE
Problems with Quick Start Guide

### ISSUE THREAD

**Issue by gargnupur** [istio/istio.github.io#1272]

**Comment by gargnupur** [comment]
Sorry.. sent too soon.. will add issues in this bug..

**Comment by gargnupur** [comment]
1) Open Shift Origin Cloud(https://preliminary.istio.io/docs/setup/kubernetes/quick-start.html#openshift-origin-version-37-or-later):

I followed steps here to setup this cloud(https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#mac-os-x-with-docker-machine) and then deployed latest Istio 0.8 RC(https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-0.8-20180504-17-20/)
But all commands listed in this section failed with following error:
Error from server (NotFound): the server could not find the requested resource (get securitycontextconstraints.security.openshift.io anyuid)
Looking around about this error, it looks like it should be installed using ansible but those instructions are not clear(https://github.com/openshift/origin/issues/10367)

Also, the list of services and pods are different..
gargnupur-macbookpro:istio-release-0.8-20180504-17-20 gargnupur$ kubectl get svc -n istio-system

NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                                               AGE

istio-citadel              ClusterIP      10.63.255.62    <none>         8060/TCP,9093/TCP                                                     4m

istio-egressgateway        ClusterIP      10.63.242.49    <none>         80/TCP,443/TCP                                                        4m

istio-ingress              LoadBalancer   10.63.243.117   35.192.44.44   80:30523/TCP,443:32368/TCP                                            4m

istio-ingressgateway       NodePort       10.63.240.154   <none>         80:31380/TCP,443:31390/TCP,31400:31400/TCP                            4m

istio-pilot                ClusterIP      10.63.243.74    <none>         15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   4m

istio-policy               ClusterIP      10.63.252.209   <none>         9091/TCP,15004/TCP,9093/TCP                                           4m

istio-statsd-prom-bridge   ClusterIP      10.63.240.247   <none>         9102/TCP,9125/UDP                                                     4m

istio-telemetry            ClusterIP      10.63.245.166   <none>         9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 4m

prometheus                 ClusterIP      10.63.247.244   <none>         9090/TCP                                                              4m

gargnupur-macbookpro:istio-release-0.8-20180504-17-20 gargnupur$ kubectl get pods -n istio-system

NAME                                        READY     STATUS    RESTARTS   AGE

istio-citadel-55f7b5656b-xjtm4              1/1       Running   0          5m

istio-egressgateway-687c8c84dc-gxfbg        1/1       Running   0          5m

istio-ingress-6c7bf6c467-7qt94              1/1       Running   0          5m

istio-ingressgateway-859dddd5b7-vr55p       1/1       Running   0          5m

istio-pilot-64d47bd889-mvrgb                2/2       Running   0          5m

istio-policy-59bccd8df5-tfvlm               2/2       Running   0          5m

istio-statsd-prom-bridge-6dbb7dcc7f-mdz4t   1/1       Running   0          5m

istio-telemetry-849f66c47c-twn6k            2/2       Running   0          5m

prometheus-586d95b8d9-wzspw                 1/1       Running   0          5m

**Comment by ymesika** [comment]
We've updated the 0.8 docs pretty much since you opened this issue.
Can you please let us know if something is still inaccurate there?

**Comment by jasmine-jaksic** [comment]
Closing this issue. @gargnupur please open a new one if you find deficiencies in 0.8 docs.
