### ISSUE TITLE
Document a traffic management migration task from v1alpha1 to v1alph3

### ISSUE THREAD

**Issue by linsun** [istio/istio.github.io#1273]
- use conversion tool to convert to new plan
- deploy new plan
- scale up # of replicas as needed
- roll out envoy v2 image on the deployments for a given app deployed into the mesh.  Hope old side car has old route rule in effect, new side car has new rule in effect.
- scale down # of replicas as needed.

**Comment by geeknoid** [comment]
Is this still relevant and/or worth it?
