### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [istio/istio.github.io#1274]
Greetings, 

I was sent here after proposing a logo to the wrong repo of the @istio site
now I'm here to let you know that I'd like to collaborate with the project
by delivering a logo that suits the project and hopefully It'll be a great help
for this project!

I'm Just a Graphic Designer but also a Open Source Enthusiast!

Cheers!
- Luigi.

**Comment by geeknoid** [comment]
Hi Luigi,

We're not currently looking for a new logo, but we could use some art on our web site (istio.io). Would you be interested?

**Comment by LuigiBaute** [comment]
I'll consider it all tho my goal is to help open source projects with logotypes to improve my portfolio!

I'll close this issue for now, I'll reopen when I can start helping with this really cool project!
