### ISSUE TITLE
Bookinfo doc with auto-injection misses instruction

### ISSUE THREAD

**Issue by andraxylia** [istio/istio.github.io#1303]
Automatic injection is not enabled by default, even when sidecar injector is deployed.

Bookinfo instuctions must tell the user to label the namespace so that injection works.

**Comment by andraxylia** [comment]
@hklai please add kind/blocking release label or some other way to indicate priority of doc issues.

**Comment by frankbu** [comment]
Duplicate of https://github.com/istio/istio/issues/6957
