### ISSUE TITLE
Replace name with host for subsets

### ISSUE THREAD

**Issue by andraxylia** [istio/istio.github.io#1306]
The cat command here does not work becayse name has been replaced with host:
https://preliminary.istio.io/docs/tasks/traffic-management/request-timeouts.html

Also, must be changed whereever the output of VirtualService is displayed.

Ideally, create files for those rules for maintainability.

**Comment by ymesika** [comment]
Updated in #1342

**Comment by jasmine-jaksic** [comment]
Closing this issue. @andraxylia feel free to reopen if you still encounter this issue.
