### ISSUE TITLE
istio-demo.yaml does not exist

### ISSUE THREAD

**Issue by wattli** [istio/istio.github.io#1321]
The tutorial (https://preliminary.istio.io/docs/setup/kubernetes/quick-start.html) mentions to install control plane by "kubectl apply -f istio-demo.yaml", but istio-demo.yaml does not exist in the daily package: https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-0.8-20180517-03-38/

@hklai , please feel free to reassign.

**Comment by wattli** [comment]
@hklai , @jasmine-jaksic , we need to fix this before 0.8 release

**Comment by hklai** [comment]
The doc was updated after the RC was cut.
https://github.com/istio/istio.github.io/pull/1304/files

**Comment by wattli** [comment]
Does it mean it will work for the next daily release ?

**Comment by hklai** [comment]
I expect so. Daily release test was failing due to the exact change (i.e. istio.yaml is replaced by istio-demo.yaml), hence no daily release today.

**Comment by wattli** [comment]
ok, nice to hear. And actually the productpage cannot be open in url. Hope it's the same cause.

**Comment by wattli** [comment]
The 0520 daily build has istio-demo.yaml, verified.

**Comment by leonsp** [comment]
I ran into the same error for a different reason while following a tutorial.

The command needs to be run from your istio install folder in order for `kubectl` to find `istio-demo.yaml`. e.g. `/Users/$(whoami)/istio-*` on Mac

**Comment by pedroarthur** [comment]
> The 0520 daily build has istio-demo.yaml, verified.

this file should exist in a git clone? Or do I need an actual release to get this file? I did:

    git clone https://github.com/istio/istio
    cd istio
    git checkout 1.1.3
    for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
    kubectl apply -f install/kubernetes/istio-demo.yaml
    error: the path "install/kubernetes/istio-demo.yaml" does not exist

**Comment by linsun** [comment]
This file is generated so it is in release archive but not in git.
