### ISSUE TITLE
v1alpha3 in istio 0.7 documentation

### ISSUE THREAD

**Issue by jsenon** [istio/istio.github.io#1335]
If I'm right traffic v1alpha3 is not available if you don't use proxyv2. 

Could we add warning in the documentation or delete section mentioning  v1alpha3 and link this part only for v0.8?

**Comment by geeknoid** [comment]
Frank, it's your call.

We're just about to switch istio.io to have the 0.8 content, and 0.7 will be moved into the archive, so this would be of short-term value to fix.

If we do want to fix this, the fix would have to be done in the release-0.7 branch.

**Comment by frankbu** [comment]
This doesn't seem worth it, since 0.8 is only days away now.
