### ISSUE TITLE
Istio 0.8: istio sidecar injection

### ISSUE THREAD

**Issue by jsenon** [istio/istio.github.io#1337]
Following [documentation](https://preliminary.istio.io/docs/setup/kubernetes/sidecar-injection.html#installing-the-webhook): proxyv2 is not used with helm installation

Could we update documentation with:

`helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set sidecar-injector.enabled=true --set global.proxy.image=proxyv2 > istio.yaml`

**Comment by linsun** [comment]
This is not really needed after this PR is in 5741
