### ISSUE TITLE
Istio Prelim 0.8 Guide Should Clarify Setup of Routes with Minikube & VirtualBox

### ISSUE THREAD

**Issue by ymesika** [istio/istio.github.io#1368]
@brian-avery commented on [Fri May 25 2018](https://github.com/istio/issues/issues/357)

**Is this a BUG or FEATURE REQUEST?:** 
Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: 
Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.2.12
GitRevision: 998e0e00d375688bcb2af042fc81a60ce5264009
GitBranch: release-0.2
User: releng@0d29a2c0d15f
GolangVersion: go1.8.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Is Istio Auth enabled or not ?**
Istio Auth is Not enabled.

Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
Installed istio-demo.yaml.

**What happened**
The ingress host returned by the "Control Ingress Traffic" section of the Istio Prelim 0.8 guide is not addressable without using the ip from "minikube ip" or setting up a manual route on the host system. Adding the route is not documented.

**What you expected to happen:**
Documentation should include a step to set up the route.

**How to reproduce it:**
* Follow the setup guide here: https://preliminary.istio.io/docs/setup/kubernetes/quick-start.html (using Minikube and VirtualBox)
* Proceed to the "Control Ingress Traffic" task here: https://preliminary.istio.io/docs/tasks/traffic-management/ingress.html. 
* Observe that the IP address given in "Determining the ingress IP and ports for a nodePort ingress gateway" is an ip address belonging to the VirtualBox natted interface and is not addressable without setting up a route as follows: route add -host 10.0.2.15 dev vboxnet0 where 10.0.2.15 is the INGRESS_HOST IP.

**Feature Request:**
N

**Describe the feature:**

**Comment by frankbu** [comment]
Docs have been updated to use `minikube ip` in this case.
https://preliminary.istio.io/docs/tasks/traffic-management/ingress/#determining-the-ingress-ip-and-ports-when-using-a-node-port
