### ISSUE TITLE
Installing Istio: 'Verifying the installation' missing service

### ISSUE THREAD

**Issue by ahmetb** [istio/istio.github.io#137]
> ![image](https://cloud.githubusercontent.com/assets/159209/25865892/695f0dae-34a9-11e7-96dd-3d4da99133b4.png)

My output has `istio-egress`. It's missing from the docs output.

```
➜  kubernetes git:(master) kg svc
NAME            CLUSTER-IP     EXTERNAL-IP      PORT(S)                       AGE
istio-egress    10.3.245.113   <none>           80/TCP                        6m
istio-ingress   10.3.241.55    104.199.102.48   80:30945/TCP                  6m
istio-manager   10.3.243.12    <none>           8080/TCP,8081/TCP             6m
istio-mixer     10.3.252.130   <none>           9091/TCP,9094/TCP,42422/TCP   6m
```

**Comment by ahmetb** [comment]
Similarly, `kubectl get pod` output is missing `istio-egress-*` pod too.


> ![image](https://cloud.githubusercontent.com/assets/159209/25865943/974ebfc0-34a9-11e7-81eb-f4b3739d8419.png)

**Comment by kyessenov** [comment]
#142
