### ISSUE TITLE
BookInfo: command not working on ZSH

### ISSUE THREAD

**Issue by ahmetb** [istio/istio.github.io#139]
https://istio.io/docs/samples/bookinfo.html

    export GATEWAY_URL=$(kubectl get po -l istio=ingress -o jsonpath={.items[0].status.hostIP}):$(kubectl get svc istio-ingress -o jsonpath={.spec.ports[0].nodePort})

this commands work on Bash but errors out on ZSH:

```
zsh: no matches found: jsonpath={.items[0].status.hostIP}
zsh: no matches found: jsonpath={.spec.ports[0].nodePort}
```

**Comment by kyessenov** [comment]
Right, we need quotes ("") since zsh is more picky about expansions.
Thanks for reporting!
@andraxylia

**Comment by kyessenov** [comment]
#143
