### ISSUE TITLE
Create a Wikipedia entry for Istio

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#140]
We should pour content into WIkipedia. K8s has a nice page, we should have ours too.

**Comment by rshriram** [comment]
Really? Isn't it a bit early @geeknoid? We might get flagged as self promoting until someone from outside contributes.

**Comment by ldemailly** [comment]
In my experience, you need press and 'credible source' links (not internal sites/links, pr
or tweets) to get a wikipedia entry 
and typically has to come from outside the team making the thing described

**Comment by ahmetb** [comment]
exactly what @ldemailly said. First you need to be encyclopedia-worthy otherwise your self-submitted page will get removed soon.
