### ISSUE TITLE
Issue with docs/setup/kubernetes/quick-start-gke-dm.md

### ISSUE THREAD

**Issue by mukundha** [istio/istio.github.io#1410]
[GKE Deployment manager](https://raw.githubusercontent.com/istio/istio/master/install/gcp/deployment_manager/istio-cluster.jinja&followup=https://console.cloud.google.com/launcher/config?templateurl=https://raw.githubusercontent.com/istio/istio/master/install/gcp/deployment_manager/istio-cluster.jinja&flowName=GlifWebSignIn&flowEntry=ServiceLogin)  has only support for 0.6 & 0.5, can we add support for the newer releases?

**Comment by geeknoid** [comment]
@salrashid123

**Comment by salrashid123** [comment]
pls see:
* template https://github.com/istio/istio/pull/6010
* docs https://github.com/istio/istio.github.io/pull/1437
