### ISSUE TITLE
Flag --includeIPRanges has been deprecated

### ISSUE THREAD

**Issue by gyliu513** [istio/istio.github.io#1433]
```
[root@gyliu-icp-1 istio-0.8.0]# istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
[root@gyliu-icp-1 istio-0.8.0]# istioctl kube-inject -f samples/sleep/sleep.yaml --includeIPRanges=10.0.0.1/24 -osleep2.yaml
Flag --includeIPRanges has been deprecated, Use --injectConfigMapName or --injectConfigFile instead
```

But the document here https://preliminary.istio.io/docs/tasks/traffic-management/egress/#calling-external-services-directly still using `--includeIPRanges`.

/cc @geeknoid @linsun

**Comment by linsun** [comment]
@vadimeisenbergibm could you comment on this?   Should we advise folks to use the new allowAny option?

cc @costinm @rshriram @frankbu

**Comment by gyliu513** [comment]
I still prefer that we can enable end user can use parameters but not only configmap or configfile which is more easy to use.

**Comment by imjoey** [comment]
@gyliu513  Adding the annotation `traffic.sidecar.istio.io/includeOutboundIPRanges: "172.21.0.0/20"` for pods definition in `Deployment` yaml could also take effect, which is much more simple than the flags `--injectConfigMapName` and  `--injectConfigFile`. Maybe this method could be added to official document.

By the way, the same happens to flag `--debug`. But I could not find the similar approach to make the `curl` available in `istio-proxy` sidecar container. Any solutions for this? Thanks.

**Comment by vadimeisenbergibm** [comment]
@linsun @gyliu513 let me check this

**Comment by gyliu513** [comment]
@imjoey  based on my test, the istio-proxy have `curl` available by default now with 0.8, can you check?

**Comment by mandarjog** [comment]
individual arguments are hard to audit and store, so using `--injectConfigFile` is preferred. 
You can customize the template in any way you like and then you it for inject.

Deployment/pod annotations `traffic.sidecar.istio.io/*`  is the preferred way to provide specific overrides for these parameters.

**Comment by imjoey** [comment]
@gyliu513 It seems to be missing in my case. Kind of weird.

```bash
[root@iZ2 ~]# kubectl exec -it web-mall-v1-b9889d49-89fs5 --container istio-proxy -- curl
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:262: starting container process caused "exec: \"curl\": executable file not found in $PATH"

command terminated with exit code 126
```

Istio version:
```
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```

I upgraded to v0.8.0 from v0.7.1 by following https://istio.io/docs/setup/kubernetes/upgrading-istio/ . Always without auth and sidecar-autoinjection enabled. I **did not** upgrade the sidecar image to `docker.io/istio/proxyv2:0.8.0` from `docker.io/istio/proxy:0.8.0`. So, did I miss something?

**Comment by gyliu513** [comment]
@imjoey I was using `docker.io/istio/proxyv2:0.8.0` and it always have the curl command.

**Comment by imjoey** [comment]
@gyliu513  OK, thanks. I'll upgrade the proxy image soon. 😄

**Comment by geeknoid** [comment]
Can this issue be closed, or is there still more to do here?
