### ISSUE TITLE
Update request routing usage docs to use -mtls.yaml  if mTLS was enabled

### ISSUE THREAD

**Issue by salrashid123** [istio/istio.github.io#1452]
We'll want to update the docs here
https://istio.io/docs/tasks/traffic-management/request-routing/

to show the commands to apply if mTLS was enabled

eg, use 
```istioctl create -f samples/bookinfo/routing/route-rule-all-v1-mtls.yaml```
instead

**Comment by salrashid123** [comment]
btw, i have an exsting open PR (#1437).  I can add this minor change in for the ```release-0.8``` branch.
after that, i'll add one in for ```master``` if the same applies for ```1.0``` onward.
any objections to combining into the one PR cited?

**Comment by geeknoid** [comment]
SG
