### ISSUE TITLE
Task missing cleanup step

### ISSUE THREAD

**Issue by ahmetb** [istio/istio.github.io#155]
https://istio.io/docs/tasks/integrating-services-into-istio.html is missing cleanup instructions.

Consider adding:

    kubectl delete -f apps.yaml

**Comment by ahmetb** [comment]
This task is missing cleanup step too: https://istio.io/docs/tasks/ingress.html and the next task expects you to start from scratch.

**Comment by sakshigoel12** [comment]
@ijsnellf  how far we are on this one?

**Comment by gyliu513** [comment]
After https://github.com/istio/istio.github.io/issues/155 merged, then we can close this one. @sakshigoel12
