### ISSUE TITLE
Tasks missing "source istioctl.VERSION" requirement for "istioctl inject" to work

### ISSUE THREAD

**Issue by ahmetb** [istio/istio.github.io#156]
I keep getting error

    source ../../../istio.VERSION

on various tasks such as https://github.com/istio/istio/blob/master/demos/apps/httpbin/README.md 

If this step is required consider adding to all samples.

**Comment by andraxylia** [comment]
This issue will be fixed in the code pre-alpha release, by fix to  istio/manager#568
