### ISSUE TITLE
Use inline scripts to fetch external IPs in tasks

### ISSUE THREAD

**Issue by ahmetb** [istio/istio.github.io#157]
See the screenshot below:

- if I'm using NodePort, it provides me a handy script
- if I'm using external IP, it tells me to copy paste.

Why is there such a difference? I believe the latter can be achieved with a handy inline script too.

![image](https://cloud.githubusercontent.com/assets/159209/25913353/4aaa63e2-356f-11e7-8c29-96f97c4123d5.png)

**Comment by ldemailly** [comment]
this is on 
https://github.com/istio/istio.github.io/blob/master/_docs/tasks/ingress.md

**Comment by ldemailly** [comment]
it seems we are not doing this. if you feel it's needed reopen
