### ISSUE TITLE
Update “Setup/Performance and Scale” section for istio.io

### ISSUE THREAD

**Issue by jasmine-jaksic** [istio/istio.github.io#1575]
@jasmine-jaksic commented on [Fri Jun 22 2018](https://github.com/istio/istio/issues/6534)

As part of doc items needed for 1.0, add a section that describes the consideration and techniques for scaling a mesh.

Refer to: https://docs.google.com/document/d/1WSmAwmVBoGoGz5Hek5rGK1JnXjnGKdCO9tqpbvv9404/edit#

**Comment by ldemailly** [comment]
https://github.com/istio/istio.github.io/issues/911 was "add" what remains is improvements and update for 1.0 data - #1377 (possibly reshuffle if we want a different layout)

**Comment by jasmine-jaksic** [comment]
@suryadu @geeknoid is there anything else that need to be added to perf section, other than what's listed in #1377?

**Comment by jasmine-jaksic** [comment]
@dcberg @suryadu Has there been any progress on this so far?

@geeknoid Given that a page already exists, I'm going to downgrade this to P1. Let me know if you disagree.
