### ISSUE TITLE
Issues for referencing svg files from Chinese Content

### ISSUE THREAD

**Issue by gyliu513** [istio/istio.github.io#1602]
In order for easy maintain, for all of the Chinese content, I prefer that we use a symlink for the svg files and link it from English content to Chinese content, this is easy to maintain, as once the svg files are updated sometime, the Chinese content will be updated automatically.

/cc @geeknoid @rootsongjc @fleeto 

Please show your comments if any.

**Comment by fleeto** [comment]
Perhaps it's not a good option. 
When  an image in the original version is updated, the text in it will be changed together, they should be updated in the same time. Keeping the same images only means nothing. 
The The most stupid way is to copy images to zh, and reference them with the related path like 'img/abc.png'. This approach is more stable and independent.

Or we can do nothing about image files, we just put the reference to the original image in the master tree.

**Comment by geeknoid** [comment]
If you're going to do a symlink to the original, then why not just use an absolute link in the markdown file instead? That is link="/docs/concepts/overview/foo.svg"

**Comment by gyliu513** [comment]
Thanks @fleeto and @geeknoid 

Using symlink can enable us do not change the file location but just copy the location directly from english version. Using absolute link will request all links in Chinese document needs to be updated which is different with english version. So seems using symlink is better?

**Comment by fleeto** [comment]
I think copy images to zh folders is the best, sharing data is not the style of microservices :)
And the 2nd way , as @geeknoid said, just ` link="/docs/concepts/overview/foo.svg"`

**Comment by gyliu513** [comment]
OK, then I think we can go ahead with the solution of using absolute path. @fleeto @geeknoid @rootsongjc

**Comment by rootsongjc** [comment]
What should we do right now? At least it works nowadays. Should we change the pictures reference?

**Comment by geeknoid** [comment]
Can we close this then?

**Comment by gyliu513** [comment]
yes, let me close this one. Thanks all for the comments here.
