### ISSUE TITLE
Inaccurate instructions to setup INGRESS_HOST environment variable

### ISSUE THREAD

**Issue by ymesika** [istio/istio.github.io#1603]
@arun-gupta commented on [Wed Jun 27 2018](https://github.com/istio/istio/issues/6663)

Instructions to setup `INGRESS_HOST` at https://istio.io/docs/tasks/traffic-management/ingress/#determining-the-ingress-ip-and-ports says:

```
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
```

Where as, what worked was:

```
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
```

**Comment by sdake** [comment]
I think this is platform dependent unfortunately.  ip works for me, but hostname does not.

**Comment by gyliu513** [comment]
Yes, I was using https://github.com/gyliu513/work/tree/master/k8s/charts/keepalived , and the ip works fine in my case.

Perhaps we need add some option in the document to let customer select the command based on their requirement.

**Comment by arun-gupta** [comment]
A clarification would be really helpful
