### ISSUE TITLE
Should we bulk-machine-translate the site?

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#1612]
Would it be useful to use machine translation to do a first pass of translating all web site content, and then use humans to fix that up? Is our techno-jargon too much for machine translation at this point?

@rootsongjc WDYT?

**Comment by fleeto** [comment]
There are about 70 files left in the [queue](https://github.com/servicemesher/istio-official-translation/issues). Now the translation process works well, so we've invited more Chinese users to join the team, and they have started now, more PR is coming.

btw, @gyliu513 is the only one who can review Chinese translations, can I also join as a member?

**Comment by rootsongjc** [comment]
@geeknoid  We have a great community which can help us to translate the docs, in order to accelerate the translation process, we need to assign more members and owners for the Chinese content. We hope that the docs will have a Chinese version as istio 1.0 release.
