### ISSUE TITLE
tie releasing a new version to setting variable for download links/example / updating the docs

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#162]
I added an example of steps to get the istio binary for the downloadable binary release in 
https://github.com/istio/istio.github.io/commit/6cfbaa2647f742d9dc3eb5cf4651cba86828b6a5
but it'd be nice that example auto updates to $RELEASE_VERSION or some equivalent in jekyll

**Comment by geeknoid** [comment]
In Jekyll, we currently have the {{site.data.istio.version}} variable which is defined as 0.1. We can readily add more variables by adding entries in the _data/istio.yml file.

**Comment by ldemailly** [comment]
where is that variable set, doing a search on repo I see it being used, but not where it's set ?

**Comment by geeknoid** [comment]
in _data/istio.yml.

**Comment by sebastienvas** [comment]
@ldemailly  is this still relevant with @rshriram script ?

**Comment by ldemailly** [comment]
it's relevant if we (ever) want to include detailed manual instructions - but indeed @andraxylia removed the mention of the manual curl'ing of the download so we don't need it right now

**Comment by sebastienvas** [comment]
I think the 0.1 is good enough. We actually don't want to update the docs each time we create a patch release.
