### ISSUE TITLE
Incomplete docs section

### ISSUE THREAD

**Issue by ahmetb** [istio/istio.github.io#163]
https://istio.io/docs/tasks/ingress.html#configuring-secure-ingress-https

> ![image](https://cloud.githubusercontent.com/assets/159209/25915715/32596060-3577-11e7-96e4-b9506f449561.png)

**Comment by douglas-reid** [comment]
remove understanding altogether or beef it up.

**Comment by ijsnellf** [comment]
Also reported in #161

**Comment by ijsnellf** [comment]
Resolved by https://github.com/istio/istio.github.io/pull/203.
