### ISSUE TITLE
"Enabling Egress Traffic" doesn't explain why configure external services

### ISSUE THREAD

**Issue by ahmetb** [istio/istio.github.io#164]
Reading through https://istio.io/docs/tasks/egress.html doc, it doesn't mention anywhere  what I’m configuring external services such as `httpbin.org`.

Is it mandatory (i.e. does envoy/istio block me from accessing external services?) or is it because of some limitation (e.g. proxy can't intercept tls traffic) or is it just good practice.

I think this needs clear explanation.

**Comment by frankbu** [comment]
Fixed with #189
