### ISSUE TITLE
Update docs to support 3 separate user journeys

### ISSUE THREAD

**Issue by andraxylia** [istio/istio.github.io#166]
There are too many if-else in the documents, which require too much thinking from first- time users.

Restructure into 3 user journeys and create 3 workflows:

- want to try istio (no auth or complicated things), with the book info to show features
- want to understand how it works and try some advanced features but I am not committed - with a simpler echo server with which people are familiar
- production level workflow with advanced features

This requires re-introducing something similar to the echo app for the second workflow.

**Comment by sakshigoel12** [comment]
@andraxylia how far are we on this? Can we add an ETA?

**Comment by andraxylia** [comment]
We simplified installation, closing this.
