### ISSUE TITLE
Improve layout of landing page

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#167]
The layout of the landing page is way too tall. It takes a fair bit of scrolling to see all the major features of the product. Someone in a hurry wouldn't even notice it doesn't more than L7 load balancing. We need to reorganize the landing page to bring key info above the fold.

**Comment by davetropeano** [comment]
I don't think this is a webpage layout HTML/CSS/JS thing. I think this is a presales/copywriting issue.

Typically with a landing page you want to summarize the product and make your initial "presales" pitch above the fold -- i.e. without requiring the user to scroll...

The bands we have are four features but there should be a top introduction with maybe an image or video that introduces istio and makes the reader want to scroll for more.

**Comment by geeknoid** [comment]
Related to issue #278
