### ISSUE TITLE
CI process is blocked for days

### ISSUE THREAD

**Issue by fleeto** [istio/istio.github.io#1670]
#1669 #1652 #1659 ...
Chinese translation has been blocked for a few days.

Same logs appeared in CI console of each PR:

~~~
- ./public/docs/tasks/telemetry/fluentd/index.html
  *  213:53: ERROR: Unexpected end tag : p (line 213)
~~~

**Comment by rootsongjc** [comment]
All of the PRs are blocked, see the [list](https://github.com/servicemesher/istio-official-translation/projects/2#column-2980860)

**Comment by geeknoid** [comment]
Tests are now passing.
