### ISSUE TITLE
Make the web site look good on mobile devices

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#168]
We need the site to be usable on mobile devices. Shrinking down the browser width doesn't currently produce good outcomes. We need to choose whether we want to target iPads, iPad-mini, and/or phones. Basically we need to revisit where breakpoints in CSS are and whether responsive design pieces in Bootstrap were left out.

**Comment by davetropeano** [comment]
I think I have all the breakpoints in and reasonable changes for iphone6, ipad, and ipad plus under both landscape and portrait screen resolutions.

On an iphone 6 in portrait the tabs are acceptable but I don't like them. We and prototype using a dropdown there and swap the visibility of the tabs vs a dropdown based on screen width. But I think it's acceptable as-is.

**Comment by geeknoid** [comment]
Looks good.

Let's open separate bugs for distinct issues as they emerge.
