### ISSUE TITLE
Quickstart Guide

### ISSUE THREAD

**Issue by andraxylia** [istio/istio.github.io#17]
CUJ breakdown: installation; enabling &auth; routing & policy changes

**Comment by rshriram** [comment]
I don't think we can showcase auth. The way it is today, there isn't anything useful for enduser. Traffic can't enter or leave istio app when auth is enabled.

**Comment by kyessenov** [comment]
Istio auth + ingress seems to be off alpha list. May happen by then but not a blocker. In that case, yes, the auth demo is not helpful for the end-user.

**Comment by geeknoid** [comment]
Can this issue be closed now that the installation guide is checked in?
