### ISSUE TITLE
Citadel health checking should be updated

### ISSUE THREAD

**Issue by ymesika** [istio/istio.github.io#1727]
Following https://github.com/istio/istio/issues/6922
Depends on https://github.com/istio/istio/pull/6961

Two updates:
1. The [Before you begin](https://preliminary.istio.io/docs/tasks/security/health-check.html#before-you-begin) section shouldn't have the option to install from `istio-auth.yaml` as it isn't part of releases anymore
1. When installing or templating Istio using Helm in the [Before you begin](https://preliminary.istio.io/docs/tasks/security/health-check.html#before-you-begin) section the `--set security.healthCheckEnabled=true` flag should be added (in addition to the `global.mtls.enabled=true`.

**Comment by wattli** [comment]
@lei-tang , can you take this please? Thanks.

**Comment by lei-tang** [comment]
@wattli Sure.

**Comment by ymesika** [comment]
@lei-tang The file exists again in releases so you may want to revert your changes.

**Comment by lei-tang** [comment]
@ymesika The PR https://github.com/istio/istio.github.io/pull/1924 is created to revert the PR #1744.
