### ISSUE TITLE
Track Istio 1.0-release

### ISSUE THREAD

**Issue by danehans** [istio/istio.github.io#1736]
According to https://groups.google.com/forum/m/#!topic/istio-dev/tcDEwvBaTgw, the 1.0-release branch is being used for the 1.0 release. Currently, a disconnect between istio and istio.github.io exists because istio.github.io is tracking Istio master instead of Istio 1.0-release. This makes it difficult to validate documentation.

**Comment by jasmine-jaksic** [comment]
#1715 should fix this
