### ISSUE TITLE
Doc issue / grafana addon missing?

### ISSUE THREAD

**Issue by ymesika** [istio/istio.github.io#1739]
@krancour commented on [Tue Jul 10 2018](https://github.com/istio/istio/issues/6972)

In [Viewing the Istio Dashboard](https://istio.io/docs/tasks/telemetry/using-istio-dashboard/#viewing-the-istio-dashboard), the very first step fails:

```
$ kubectl apply -f install/kubernetes/addons/grafana.yaml
error: the path "install/kubernetes/addons/grafana.yaml" does not exist
```

---

@ymesika commented on [Tue Jul 10 2018](https://github.com/istio/istio/issues/6972#issuecomment-403873036)

With which version/release?

---

@krancour commented on [Tue Jul 10 2018](https://github.com/istio/istio/issues/6972#issuecomment-403907700)

I've looked at both v0.8.0 and the head of master.

---

@ymesika commented on [Tue Jul 10 2018](https://github.com/istio/istio/issues/6972#issuecomment-403910812)

The `release 0.8.0` has this file within the downloaded package/zip/tar.
If you work with branches then this file isn't committed. It's generated when releasing or when you run `install/updateVersion.sh`.

---

@ymesika commented on [Tue Jul 10 2018](https://github.com/istio/istio/issues/6972#issuecomment-403912646)

Sorry, my bad. We don't deliver it anymore. It's now available as a Helm chart and can be installed by enabling the `grafana.enabled` flag.
It's a doc issue so I will move this one to there.

**Comment by jasmine-jaksic** [comment]
PR in flight, closing this issue
