### ISSUE TITLE
upgrade docs could use a rev

### ISSUE THREAD

**Issue by sdake** [istio/istio.github.io#1798]
* The proxy image is recommended (instead of proxyv2)
* Sidecar injection is described.  During an upgrade, sidecar upgrade should be invisible.
* Helm upgrade commands unlisted.
* Kubernetes version listed.  We should really have a separate page which lists the requirements so the Requirements for Kubernetes, Helm, and other dependencies are not duplicated throughout the documentation.  This makes the docs more difficult to maintain.

**Comment by rcaballeromx** [comment]
@jasmine-jaksic  I'm starting to work on this now that the security docs got merged. @sdake Can you give me the path where you would want to see these docs? Is there an existing doc that I should update?

**Comment by sdake** [comment]
@rcaballeromx https://preliminary.istio.io/docs/setup/kubernetes/upgrading-istio/ is the documentation we have thus far.

Cheers
-steve

**Comment by sdake** [comment]
@rcaballeromx apologies for the terse response on July 26th.  I think we met all of these goals prior to 1.0.  I'm not sure what I meant in my https://github.com/istio/istio.github.io/issues/1798#issuecomment-408008069 response.

Going to close - if folks feel otherwise, please reopen.

Cheers
-steve
