### ISSUE TITLE
Update verifying-the-installation in installing-istio.md

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.github.io#181]
https://istio.io/docs/tasks/installing-istio.html#verifying-the-installation
hackathon feedback:

In "Verifying the installation, step 1, the command "kubectl get svc -o wide" is useful since it shows external IPs and ports.
In step 2, the getting deployments may be better than getting pods. E.g. kubectl get deploy, and then have the user look that the "AVAILABLE" column is 1 for all of them.
In , the heading "Enabling Istio Auth in Istio config".  I can't tell if this applies to Option 1 or 1 and 2?
In the step of verifying istio auth, a good final step would be to do this from the laptop, and/or from another pod in the cluster:
```
		openssl s_client -host $POD_OR_SERVICE_IP
```
	This shows that ssl is being used

“Installing on an existing cluster” Step 4: Question: What’s the difference and implication between disable vs. enable Istio Auth? Perhaps it’s better to suggest just one way of doing it, e.g., disabling Auth first so that user of this page can proceed.
“What’s Next”: Now there’s a bullet point regarding learning how to enable authentication. This should be linked to from the aforementioned step.
Would be good to add instructions for Cloud Shell using wget as sven@ outlined above and to make an alias to the istioctl path.
“Uninstalling”: Should add instructions to delete optional addons, i.e., grafana, prometheus, and servicegraph

**Comment by myidpt** [comment]
I think this issue has mixed auth and non-auth features. Can you split the auth features out and assign to me? Thanks.

**Comment by lookuptable** [comment]
@wattli is working on something similar (using openssl/tcpdump to debug/verify Istio auth). @wattli do you have an issue for what you're working on?

**Comment by myidpt** [comment]
Istio CA is not bound to a service, so `kubectl get svc -o wide` will not show the CA. We can use `kubectl get deploy`.
PR#177 and PR#263 address these issues.

**Comment by myidpt** [comment]
@mandarjog You can close this now.
