### ISSUE TITLE
Provide Cluster size guidance (cpu / mem / external load balancers)

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.github.io#182]
hackathon feedback:

If you’re using GKE, use at least 4 vCPUs (15 GB mem)
 
In the troubleshooting guide consider what happens  
* When enough CPU / MEM is not available.
* When external load balancers cannot be allocated

**Comment by ldemailly** [comment]
https://istio.io/docs/samples/bookinfo.html#before-you-begin
(now) has "If you use GKE, please ensure your cluster has at least 4 standard GKE nodes."

We could add to troubleshooting though (reopen if you feel it's needed)
