### ISSUE TITLE
Wrong metric name in "Querying Metrics from Prometheus"

### ISSUE THREAD

**Issue by ymesika** [istio/istio.github.io#1841]
@ozevren commented on [Tue Jul 17 2018](https://github.com/istio/istio/issues/7169)

https://preliminary.istio.io/docs/tasks/telemetry/querying-metrics/

Instructions ask to enter "istio_request_count", but this doesn't exist. "istio_request_bytes_count" works.

**Comment by gargnupur** [comment]
istio_request_count has been changed to istio_requests_total and https://github.com/istio/istio.github.io/pull/1742 fixed this.
