### ISSUE TITLE
Issues with docs/tasks/ingress.html

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.github.io#186]
From hackathon feedback:

- [x] Doc should include instructions for httpbin:
```
cd demos/apps/httpbin
kubectl apply -f <(istioctl kube-inject -f httpbin.yaml)
```
- [x] sample response is missing (in place of current: .. response ..)
- [ ] Use of `cat <<EOF | kubectl create -f -` is inconsistent with previous tutorials, where config was saved to files first.
- [x] $INGRESS_URL is exported with port :80, but then it’s being used in secured-ingress example, where connections should be made over port :443 for HTTPS.
- [x] /html endpoint is terrible example to use with curl, since it just emits snippet from “Moby Dick”, which is very confusing output to see.
- [ ] timeout example should include upstream request timeout in the output.
- [x] https://istio.io/docs/tasks/ingress.html#understanding- is missing content.
- [x] Missing cleanup instructions to remove services installed in this tutorial.

**Comment by ijsnellf** [comment]
@mandarjog: Could you make those bullets numbered so we can reference them?

**Comment by ijsnellf** [comment]
Never mind, I was given privileges and updated the comment.

**Comment by mandarjog** [comment]
more feedback:
[] Access the httpbin service using curl - returned no headers
[] Access the secured httpbin service using curl - would hang without doing anything
