### ISSUE TITLE
{CLUSTER_NAME} is undefined on control plane

### ISSUE THREAD

**Issue by sdake** [istio/istio.github.io#1898]
```
cd $WORK_DIR
kubectl create secret generic ${CLUSTER_NAME} --from-file ${CLUSTER_NAME} -n ${NAMESPACE}
kubectl label secret ${CLUSTER_NAME} istio/multiCluster=true -n ${NAMESPACE}
```
from:
https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/#instantiate-the-credentials-for-each-remote-cluster

**Comment by sdake** [comment]
$WORK_DIR and ${NAMESPACE} are also undefined.

**Comment by tiswanso** [comment]
The values are defined in this section:  https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/#generate-kubeconfigs-for-remote-clusters

Maybe we need to clarify that the values are from that section.  If the user uses the same shell and just switch between clusters using `kubectl config use-context <cluster context>` the env vars would be still set.  But if the user is using a different set of shells then these values wouldn't be defined in both shells after running the instructions in that section.

**Comment by sdake** [comment]
@tiswanso agree - I am using the second workflow which is probably the cause of confusion.  The docs don't mention anything about `use-context`.  Whatever can be done to simplify the docs would be great 👍 .  Most people reading these docs will cut and paste, and not apply a whole lot of reasoning to their actions and expect things to work.  It took me a few hours (and I'm familiar with this stuff) to sort out the workflow using separate shells.
