### ISSUE TITLE
Deploying CA section _docs/tasks/istio-auth.md

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.github.io#190]
hackathon feedback:
* Typo erro “Deplying CA” on page https://istio.io/docs/tasks/istio-auth.html#deplying-ca
* Path mentioned for the file “kubernetes/istio-auth/istio-cluster-ca.yaml” @ https://istio.io/docs/tasks/istio-auth.html#deploying-ca seems to be incorrect. From what I downloaded and extracted from istio-0.1.0.zip the path seems to be - kubernetes/templates/istio-auth

**Comment by lookuptable** [comment]
Oliver is working on a fix for this #177

**Comment by myidpt** [comment]
It's fixed by #177 . We can close it.

**Comment by myidpt** [comment]
@mandarjog You can close this issue now.
