### ISSUE TITLE
Issues with istio-installation.md

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.github.io#192]
from hackathon feedback:

installing-istio:
* Installation link for kubectl in the prerequisites. Useful for the option of using google container engine. 
* Better to mention that both source and istioctl tars has to be extracted in step 1 (installation on existing cluster)
* Better to have absolute links with home directory reference like (<ISTIO_HOME/) in all the kubectl steps (kubectl apply -f <istio_home>/isitio-1.0/install/kubernetes/addons/grafana.yaml)
* Good to mention the optional components (like grafana) in the list svc and pod (steps 1 and 2 verifying installations)

**Comment by ldemailly** [comment]
this is fixed in https://github.com/istio/istio.github.io/pull/198 and later

**Comment by andraxylia** [comment]
I did not close it on purpose, there are a couple of things left.

**Comment by ldemailly** [comment]
ah sorry, what's left ?
