### ISSUE TITLE
Evaluate whether Chinese is ready for 1.0

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#1923]
Istio 1.0 will become official on July 31. Do we believe the Chinese translation is in good enough shape to feature it in the 1.0 timeframe? The English docs have been evolving quickly and will likely continue to evolve, so can we ensure the Chinese version is up to date and reflects all changes accurately?

What should we do about the reference documentation? This documentation is generated from the protos in istio/api and istio/istio, and the command-line information from commands in istio/istio. Should we just drop English versions of that material within the Chinese section.

Aside from the translation of the content, there are two points of integration for Chinese into the web site:

- Chinese is listed as an option in the gear menu. Selecting this sets a cookie so the language choice is remembered.

- Netlify automatically serves Chinese content to a Chinese user, unless an explicitly language cookie has been saved. This feature is not currently enabled, we just need to comment out a line in netlify.toml to enable this behavior.

If we want to disable Chinese for 1.0, we'll just remove the entry from the gear menu. Users will still be able to directly navigate to the Chinese content at istio.io/zh. If we want to enable Chinese for 1.0, we'll want to update netlify.toml to allow Netlify to process the language cookie and automatically direct the user to the right language.

So what do you think guys? Can we complete the translation and get to a sufficient level of quality by the 31st? Or should we disable Chinese for 1.0 and target to enable it a bit later?

**Comment by rootsongjc** [comment]
Hi, Martin and [ServiceMeshers](https://github.com/servicemesher), I think it's okay to release the Chinese docs when Istio 1.0 becomes official. That's should be a big news.

I prefer the second way. [This](https://github.com/servicemesher/istio-official-translation/projects/2) is the current translation progress, you can see that there'e only a few part need to be translated, we will check the updates and perfect the Chinese docs in the next few days and hope that we can be representatives of the Chinese community to attract more Chinese people to join our Istio community.

When Chinese users log on to this website If they can see perfect Chinese documents, it hints that there are a lot of Chinese people involved in this project, so they will have more confidence in the project.😄

**Comment by geeknoid** [comment]
Note that content_zh currently contains many links that point back to English content. I think someone needs to do a cleanup pass to make sure Chinese content refers back to Chinese content.

**Comment by rootsongjc** [comment]
I will check the whole contents in content_zh  tomorrow.

**Comment by fleeto** [comment]
I'd like to  choose the language manually, and it would be better if the language button could be conspicuous.

**Comment by rootsongjc** [comment]
Both methods are OK, no matter leave the users to choose language manually or present Chinese content to them directly, we should make the user know that there is Chinese content there. @fleeto We will inform it to Chinese people throught [ServiceMesher](http://www.servicemesher.com) community.

**Comment by gyliu513** [comment]
+1 to choose language manually, and I also think the 1.0 Chinese document should also be released together with Istio 1.0 announcement, this can attract more Chinese users.

**Comment by rootsongjc** [comment]
@fleeto is working on this. @geeknoid As the links in Chinese contents head to the English docs now, how do we make it redirect to the right Chinese pages?

**Comment by fleeto** [comment]
About the links:

There are 4 kinds of links:
1. external url: `http://ext.url/page.htm`
2. internal image: `link="/docs/image.svg"`
3. internal page reference: `![page][/docs/page/]`
4. internal anchor reference: `![pae][/docs/page/#anchor]`

Here is my opinion:

- Type 1 & 2, just keep it;
- Type 3, search -> validate -> replace, can be done by script;
- Type 4, #anchor should be replaced into Chinese version, it seems that we can only pick it out and then edit it manually .

**Comment by geeknoid** [comment]
@fleeto Yep, I agree, that's what you have to do.

**Comment by geeknoid** [comment]
Release is tomorrow. I'm worried that the Chinese content is incomplete, and it doesn't contain a lot of the latest content including the blog posts and other changes which will be coming tonight.

I feel uncomfortable having docs which aren't complete and contain many known errors (that have been fixed in English). I think we should remove the language selection menu for the time being. The Chinese content would still be available if someone enters the URL directly, but it won't be advertised anywhere.

Then in a week or two when you guys have all caught up with the English stuff, then we can enable it and post a blog announcing the translation.

How's that sound?

**Comment by rootsongjc** [comment]
I will post the address https://istio.io/zh of the Chinese page to everyone, hoping to call for more people to participate the Chinese documentation. Will this link works https://istio.io/zh when 1.0 release? Maybe now it's not the best to advertise it officially, it's a good choice to ask the visitors to enter the URL directly, while everything is sycn to English we will add the switch button there.

**Comment by geeknoid** [comment]
Yes, that link will work. The only thing that's different is that the menu
item is gone. As soon as you guys are ready, I'll bring back the menu item
and we can publish a blog advertising the translation.
