### ISSUE TITLE
chinese translation: Please translate the platform-setup PRs:

### ISSUE THREAD

**Issue by sdake** [istio/istio.github.io#1977]
in order:
https://github.com/istio/istio.github.io/pull/1948
https://github.com/istio/istio.github.io/pull/1960

Fast action would be appreciated, as the site links to these PRs all over the place.

Cheers
-steve

**Comment by fleeto** [comment]
OK, I'll do it. #1953 had been pushed, just waiting for the #1948 and #1960, now I'll close it and make new PRs.

**Comment by rootsongjc** [comment]
@sdake Can we close this issue now?

**Comment by sdake** [comment]
@rootsongjc nice work!  Closing.
