### ISSUE TITLE
preliminary / 1.0.0 docs do not document required admission controllers for minikube

### ISSUE THREAD

**Issue by krancour** [istio/istio.github.io#2017]
Compare:

https://preliminary.istio.io/docs/setup/kubernetes/platform-setup/minikube/

to:

https://istio.io/docs/setup/kubernetes/quick-start/#minikube

And observe that critical details are missing-- namely required admission controllers are not explicitly enabled.

**Comment by andraxylia** [comment]
This got removed by @sdake , not sure where the truth lies anymore, re-assigning.
