### ISSUE TITLE
Direct HTTPS traffic through an egress gateway task may be incorrect

### ISSUE THREAD

**Issue by diemtvu** [istio/istio.github.io#2070]
Apart from missing `apiVersion: networking.istio.io/v1alpha3` for the CRD, this [task](https://preliminary.istio.io/docs/tasks/traffic-management/egress-gateway/#direct-https-traffic-through-an-egress-gateway) doesn't work for me (curl returns with `command terminated with exit code 35`)

My system set up with mTLS enabled.

**Comment by vadimeisenbergibm** [comment]
@diemtvu Could you please specify the Istio build version you used?

**Comment by diemtvu** [comment]
I use istio-release-1.0-20180730-18-29

**Comment by vadimeisenbergibm** [comment]
OK, I am testing it now on https://github.com/istio/istio/releases/tag/1.0.0, with https://github.com/istio/istio.github.io/pull/1942. Will update you.

**Comment by vadimeisenbergibm** [comment]
@diemtvu After https://github.com/istio/istio.github.io/pull/1942 is merged, the instructions will be correct for https://github.com/istio/istio/releases/tag/1.0.0.

**Comment by diemtvu** [comment]
Fix verified.
