### ISSUE TITLE
Top nav bar items shift left/right

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#213]
The About/Docs/Blog/Community/FAQ text shifts left and right depending on which page you're on.

For example, being on the istio.io/true-index.html page and clicking on Docs shifts the text to the right. Clicking on FAQ shifts it back to the left.

**Comment by davetropeano** [comment]
I think this is fixed for all but the blog page. I am not sure what the issue is with the blog page.. it will require more work.

**Comment by davetropeano** [comment]
The blog page loads a jquery validation script that has a bug in it -- it assume a signup form with an certain ID and set of fields. I took out `mc-validate.js` from the blog template for now.
