### ISSUE TITLE
oraganize helm configuration table

### ISSUE THREAD

**Issue by linsun** [istio/istio.github.io#2136]
From the helm doc file (https://preliminary.istio.io/docs/reference/config/installation-options/ ), the configuration is a huge table. We should categorize them a bit, based on category and common configurations maybe listed on the top for each category and make them bold...

Is it possible to automate this in the py file ( https://github.com/istio/istio.github.io/blob/master/scripts/tablegen.py)?

**Comment by sdake** [comment]
@linsun as I was working on a refactor for tablegen.py that I had to table for a short while, I was thinking it would be helpful to render the docs with each major section as a header (e.g.)

## Global Variables

A table

## Security variables

A table

`...`

Unfortunately I am wrapped up in other things at present, and can't immediately work on this.  I'll add to my backlog.

Cheers
-steve
