### ISSUE TITLE
Chinese linting problems

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#2149]
In PR #2148 , I disabled checks on the Chinese content since it currently has errors. To reenable, uncomment the line

#check_content content_zh --zh-cn

from scripts/lint_site.sh and fix the warnings you see.

In addition, I would like to enable a new linting rule to ensure that page descriptions end with periods. Some of the Chinese page descriptions end with 。, some don't. Should they all finish with 。like we always finish with . in English?

That lint check is currently disabled, but I'd like to turn it on if possible. To see all the issues, you can go into the file layouts/_default/baseof.html and update the following blocks at the top of the file:

        {{ with .Page.Description }}
            {{ if not (or (strings.HasSuffix . ".") (strings.HasSuffix . "。")) }}
                MARKDOWN ERROR: page description does not end with a period.
            {{ end }}
        {{ end }}

Just add the error message in there. Then regenerate the site and run the linters to see the page descriptions that don't have periods.

There are a few in the English docs/reference/* section. I'll be fixing those shortly.

**Comment by geeknoid** [comment]
You need one extra step, which is to rebuild the site before you lint it. These linting errors are detected in the final generated HTML and not in the original markdown.

When I do the changes, build the site, and then run lint, I get:

docker run -t -i --sig-proxy=true --rm -v /Users/mtail/go/src/istio.io/istio.github.io:/site -w /site gcr.io/istio-testing/website-builder:2018-07-14 scripts/lint_site.sh
mdspell 1.3.1
mdl 0.5.0
htmlproofer 3.9.1
    content_zh/docs/tasks/traffic-management/egress-gateway/index.md
       96 | stinationRule` 来指定 egress 网关的 mTLS，将 SNI 设置为 `edition.cnn.com`。 
      218 | 1.  检查  _istio-egressgateway_ pod 的日志，并查看与我们的请求对应的行。如果 Ist 
      285 | stinationRule` 来指定 egress 网关的 mTLS，将 SNI 设置为 `edition.cnn.com`。 
      416 | 1.  检查  _istio-egressgateway_ pod 的日志，并查看与我们的请求相对应的行。如果 Is 
      476 | stinationRule` 来指定 egress 网关的 mTLS，将 SNI 设置为 `edition.cnn.com`。 

>> 5 spelling errors found in 117 files
To learn how to address spelling errors, please see https://github.com/istio/istio.github.io#linting
./public/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/policy-and-telemetry/adapters/solarwinds/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/policy-and-telemetry/adapters/signalfx/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/policy-and-telemetry/adapters/statsd/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/policy-and-telemetry/adapters/list/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/policy-and-telemetry/adapters/datadog/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/policy-and-telemetry/adapters/opa/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/policy-and-telemetry/adapters/servicecontrol/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/policy-and-telemetry/templates/quota/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/config/istio.networking.v1alpha3/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/commands/pilot-discovery/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/commands/node_agent/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/commands/istioctl/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/commands/pilot-agent/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/commands/sidecar-injector/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/docs/reference/commands/istio_ca/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/about/contribute/writing-a-new-topic/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/about/contribute/terms/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/tasks/security/role-based-access-control/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/tasks/security/mtls-migration/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/tasks/policy-enforcement/denial-and-list/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/tasks/telemetry/distributed-tracing/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/tasks/traffic-management/ingress/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/tasks/traffic-management/circuit-breaking/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/tasks/traffic-management/egress-tls-origination/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/setup/consul/install/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/setup/consul/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/setup/kubernetes/spec-requirements/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/setup/kubernetes/quick-start-gke-dm/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/setup/kubernetes/platform-setup/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/setup/kubernetes/platform-setup/minikube/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/docs/setup/kubernetes/platform-setup/openshift/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2017/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2017/adapter-model/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2017/0.1-canary/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2017/mixer-spof-myth/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2018/v1alpha3-routing/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2018/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2018/egress-https/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2018/aws-nlb/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2018/traffic-mirroring/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2018/soft-multitenancy/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
./public/zh/blog/2018/egress-tcp/index.html:11:                MARKDOWN ERROR: page description doesn't end with a period
Errors found in the markdown content

**Comment by fleeto** [comment]
@rootsongjc @gyliu513 
I can't reproduce this scenario, can you try it?

**Comment by rootsongjc** [comment]
Me too, can't reproduce this issue, @geeknoid

**Comment by geeknoid** [comment]
Please see https://github.com/istio/istio.github.io/pull/2155.

**Comment by geeknoid** [comment]
Thanks for fixing.
