### ISSUE TITLE
default pod not create 

### ISSUE THREAD

**Issue by rajasekarjayapal** [istio/istio.github.io#2284]
I could see Product,Rating and Review Services in Default name space.
PS C:\mufg\istio-1.0.0> kubectl get services
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
details ClusterIP 10.100.10.177 9080/TCP 35m
eurekaserver-deployment LoadBalancer 10.100.211.163 a968daad18e56... 8761:30987/TCP 25d
guestbook LoadBalancer 10.100.21.83 ae439a52d8b5b... 3000:30545/TCP 29d
kubernetes ClusterIP 10.100.0.1 443/TCP 30d
productpage ClusterIP 10.100.11.13 9080/TCP 35m
ratings ClusterIP 10.100.188.133 9080/TCP 35m
redis-master ClusterIP 10.100.90.23 6379/TCP 29d
reviews ClusterIP 10.100.41.64 9080/TCP 35m
sleep ClusterIP 10.100.225.120 80/TCP 9m

Unable to see these Servcices in PODS.

PS C:\mufg\istio-1.0.0> kubectl get pods
NAME READY STATUS RESTARTS AGE
eurekaserver-deployment-67575b4d96-vfs87 1/1 Running 0 25d
guestbook-9jzvc 1/1 Running 0 29d
guestbook-m75sc 1/1 Running 0 29d
guestbook-vcfb2 1/1 Running 0 29d
redis-master-6mphz 1/1 Running 0 29d
redis-slave-6bv2d 1/1 Running 0 29d
redis-slave-w7lrl 1/1 Running 0 29d

I can deploy the services in istio-system namespace, where I could see these services in pods.

But unable to Enable Istio Injection.

PS C:\mufg\istio-1.0.0> kubectl label namespace istio-system istio-injection=enabled
error: 'istio-injection' already has a value (disabled), and --overwrite is false

How to enable istio-injection in namespace istio-system.

**Comment by rajasekarjayapal** [comment]
I can see Product,Rating and Review Services in Default name space.
PS C:\mufg\istio-1.0.0> kubectl get services
NAME                      TYPE           CLUSTER-IP       EXTERNAL-IP        PORT(S)          AGE
details                   ClusterIP      10.100.10.177    <none>             9080/TCP         35m
eurekaserver-deployment   LoadBalancer   10.100.211.163   a968daad18e56...   8761:30987/TCP   25d
guestbook                 LoadBalancer   10.100.21.83     ae439a52d8b5b...   3000:30545/TCP   29d
kubernetes                ClusterIP      10.100.0.1       <none>             443/TCP          30d
productpage               ClusterIP      10.100.11.13     <none>             9080/TCP         35m
ratings                   ClusterIP      10.100.188.133   <none>             9080/TCP         35m
redis-master              ClusterIP      10.100.90.23     <none>             6379/TCP         29d
reviews                   ClusterIP      10.100.41.64     <none>             9080/TCP         35m
sleep                     ClusterIP      10.100.225.120   <none>             80/TCP           9m

Unable to see these Servcices in PODS.

PS C:\mufg\istio-1.0.0> kubectl get pods
NAME                                       READY     STATUS    RESTARTS   AGE
eurekaserver-deployment-67575b4d96-vfs87   1/1       Running   0          25d
guestbook-9jzvc                            1/1       Running   0          29d
guestbook-m75sc                            1/1       Running   0          29d
guestbook-vcfb2                            1/1       Running   0          29d
redis-master-6mphz                         1/1       Running   0          29d
redis-slave-6bv2d                          1/1       Running   0          29d
redis-slave-w7lrl                          1/1       Running   0          29d

I can deploy the services in istio-system namespace, where I could see these services in pods.

But unable to Enable Istio Injection.

PS C:\mufg\istio-1.0.0> kubectl label namespace istio-system istio-injection=enabled
error: 'istio-injection' already has a value (disabled), and --overwrite is false

How to enable istio-injection in  namespace istio-system.

**Comment by geeknoid** [comment]
Please post questions to the istio-users@ mailing list. 

Thanks.
