### ISSUE TITLE
`text_dynamic` had rendered the yaml file into a single line

### ISSUE THREAD

**Issue by fleeto** [istio/istio.github.io#2502]
﻿https://istio.io/about/contribute/writing-a-new-topic/#dynamic-content

**Comment by geeknoid** [comment]
Looks fine right now. Does it still look bad for you?

**Comment by fleeto** [comment]
Hi  @geeknoid, thx.

This looks like a Firefox compatibility issue, it’s working perfect on Chrome and Safari.

![image](https://user-images.githubusercontent.com/6958477/45072473-b38f3c00-b10d-11e8-84f3-ea372da73619.png)
