### ISSUE TITLE
Left nav items can no longer be collapsed

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#251]
Clicking on collapsable items in the left nav collapses them, and then they immediately reopen again.

**Comment by davetropeano** [comment]
Hmmm.. I cannot replicate on Chrome or FF on my mac. I'll try a PC later today. It sounds like a debounce issue but like I said, I cannot repeat it just now.

**Comment by geeknoid** [comment]
Try on this page: http://istio.io/docs/reference/index.html

Click on the word API in the left nav.

**Comment by davetropeano** [comment]
Works fine for me. I'll try on a PC in a bit..

**Comment by kyessenov** [comment]
Doesn't work for me too. Chrome on mac.

**Comment by ryangrahamnc** [comment]
I'm seeing it happen. Might be related to this file thats failing to load for me:
![image](https://cloud.githubusercontent.com/assets/1237156/26219500/4254579c-3bdd-11e7-9d99-8c9351c6b66a.png)

Probably related to js/common.js:79
`$.getScript("{{ site.baseurl }}/js/jquery.collapsible.js", function(){`

the generated file _site/js/common.js still has that line without the {{site.baseurl}} var getting replaced.

Are we allowed to template variables inside of js files? Additionally, why does it appear to be inconsistent based on each dev's machine?

**Comment by geeknoid** [comment]
​Shoot, I broke this template thing last night by removing the --- front
matter on the script file. I'll add that back shortly to fix that problem.

Sadly, this won't help the collapsing left nav items. That was there before
I botched this particular template expansion.​

**Comment by davetropeano** [comment]
Maybe the inconsistency is because of caching.. I run the site in Chrome dev tools but I still think external JS files are cached.. maybe that is why I wasn't seeing it

**Comment by geeknoid** [comment]
I checked in a fix for the broken common.js.
