### ISSUE TITLE
Images causing formatting issues

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio.github.io#253]
Places where an image is added have formatting issues:
![image](https://cloud.githubusercontent.com/assets/19473346/26165275/fcfeaaa0-3af4-11e7-97c5-aef156689afa.png)

See:
https://github.com/istio/istio.github.io/blob/master/_includes/figure.html
https://github.com/istio/istio.github.io/blob/master/_docs/tasks/installing-istio.md

**Comment by davetropeano** [comment]
I just looked at ipad and various desktops and this looks OK to me on a mac in chrome + FF. I don't see a layout issue.

**Comment by geeknoid** [comment]
I removed used of figure.html since it's not compatible with markdown's "semanrtic indenting" model. :-(
