### ISSUE TITLE
Inconsistent GKE creation example and number of node suggestion

### ISSUE THREAD

**Issue by medyagh** [istio/istio.github.io#2571]
in [this page](https://istio.io/docs/examples/bookinfo/#if-you-are-running-on-kubernetes), the doc suggests to have at least 4 nodes for GKE :

```
If you use GKE, please ensure your cluster has at least 4 standard GKE nodes. If you use Minikube, please ensure you have at least 4GB RAM.
```

However in the [setup page](https://istio.io/docs/setup/kubernetes/platform-setup/gke/) the command that is used to create example GKE cluster creates them with 3 nodes.

```
 gcloud container clusters create <cluster-name> \
  --cluster-version=1.10.5-gke.4 \
  --zone <zone> \
  --project <project-id>
```

Following the example is inconstant.

**Comment by geeknoid** [comment]
@salrashid123 Could you take a look?

**Comment by salrashid123** [comment]
our suggestion is 4 nodes and its what we use on the DM template too.

however:

The gke cluster verison specifies fully qualified  `1.10.5-gke.4`
while the DM template specifies the version alias  `1.10.5` alone 

both are wrong at the moment  `1.10.5` doens't exist so deployments will fail (esp the DM version).  I'll submit an issue about it right now.

https://cloud.google.com/kubernetes-engine/versioning-and-upgrades#specifying_cluster_version

 - [istio_DM template](https://github.com/istio/istio/blob/master/install/gcp/deployment_manager/istio-cluster.jinja#L11)


We can pick either

- `1.10.6`
- `1.10.7`

LMK which one istio targets

**Comment by salrashid123** [comment]
The PR i submitted above removes the whole GKE version spec in the command.  Would recommend removing it in the gcloud command here too
