### ISSUE TITLE
missing sub-commands of istioctl in reference.

### ISSUE THREAD

**Issue by fleeto** [istio/istio.github.io#2636]
Are these commands intentionally deleted?

 `context-create, create, get, replace`

**Comment by rootsongjc** [comment]
Use `kubectl` instead?

**Comment by fleeto** [comment]
We can still see these commands in `istioctl help`, but we can't find it in the [reference](https://preliminary.istio.io/docs/reference/commands/istioct) now.

**Comment by fleeto** [comment]
Hi @geeknoid,  Any comments?

**Comment by geeknoid** [comment]
Yes, these have been deprecated. Use kubectl instead. They are marked as deprecated in the code and will be deleted completely in the 1.2 release.
