### ISSUE TITLE
Align Copy buttons to right edge of PRE block

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#264]
The Copy buttons currently stick out to the right of the PRE blocks. I think it'd all look nicer if they lined up with the PRE block instead.

**Comment by davetropeano** [comment]
So now we want to the right and not above? :)

**Comment by davetropeano** [comment]
Oh.. you want it on the top of the `<pre>` but moved over instead of fully pulled right. I get it now lol

**Comment by ldemailly** [comment]
more copy button issues:
- [ ] the p and the y of copy stick out the bottom of the highlight when mousing over
- [ ] the color is not pleasant and hard to read (of the red/brown highlight)

**Comment by geeknoid** [comment]
Kuat just changed the color, he through the orange was too hard to read I
think the new color is specifically hard to read now :-(

Regarding the button text, do you see this on all buttons or just some of
them? I was seeing variable heights between instances of the Copy button,
but that has fixed itself now and they all look the same to me.

**Comment by ldemailly** [comment]
I've put a screenshot on slack (how does one (easily) attach pictures to github issues btw?) 
it was on https://istio.io/docs/tasks/installing-istio.html
but... I shift-reloaded and they all look the same now to me as well (and the y and p are within now)

but that red needs to change - I thought what @kyessenov changed was the text inside not the copy button color (are they the same?)

**Comment by davetropeano** [comment]
You can copy/paste images with github.. works like a champ

The color is bad...lol

**Comment by ldemailly** [comment]
![screen shot 2017-05-17 at 3 55 32 pm](https://cloud.githubusercontent.com/assets/3664595/26184535/7767fcac-3b3a-11e7-956d-d920c331fee6.png)
oh nice... that's new ?

**Comment by geeknoid** [comment]
We have a new Copy button which looks nice, so this is no longer needed.

**Comment by ldemailly** [comment]
very nice indeed !
