### ISSUE TITLE
Change styles on index page content

### ISSUE THREAD

**Issue by ryangrahamnc** [istio/istio.github.io#278]
Change the margin/padding/font-size/line-height/etc on the index page

Current display:
![image](https://cloud.githubusercontent.com/assets/1237156/26221810/bfaf4578-3be5-11e7-9922-098caa6d4e0a.png)

Shooting from the hip a little on the numbers, but we'd want closer to this:
![image](https://cloud.githubusercontent.com/assets/1237156/26221817/c6a47060-3be5-11e7-9517-4e863c7d229a.png)

**Comment by davetropeano** [comment]
Looks like making the `h2` tag 3rem or so gets you there..
