### ISSUE TITLE
Bad formatting problem with TOC on istioctl page

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#279]
This page looks terrible: https://istio.io/docs/reference/commands/istioctl.html

The z-order of the PRE blocks vs. the TOC is wonky.

**Comment by geeknoid** [comment]
Also visible here: http://istio.io/docs/tasks/installing-istio.html

**Comment by geeknoid** [comment]
I reverted this change since it broke the appearance of all text blocks on the site. Some more surgically precise CSS fix is needed.

**Comment by geeknoid** [comment]
Naively, seems like an expedient fix would be to increase the Z index of the whole TOC, just to make sure it floats above everything else. I tried to do this, but alas it had no effect. So I'm probably not understanding how z ordering works in CSS. But it sure looked promising :-)

**Comment by ryangrahamnc** [comment]
https://github.com/istio/istio.github.io/pull/296
