### ISSUE TITLE
Top nav bar shifts left/right

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#283]
From the top nav bar:

Clicking between About|Docs and Blog|Community|FAQ, you can see the position of the text in the nav bar shifts left and right. Some CSS is wonky.

Additionally, if you click between sections, like going from About to Community, there is some jarring flashing happening. It appears as though the nav bar is rendered several pixels towards the right and then rerendered at its final location.

**Comment by ryangrahamnc** [comment]
I'm only seeing jumping when i do cmd+shift+r (which clears the cache and reloads). and it only does it for a split second. Are you seeing something different? Like different locations based on which page youre on? How long does it display in the first location before it jumps?

**Comment by geeknoid** [comment]
I see a small "static" shift from left to right as I click on the links. That is, once the dust settles the header for the About and Docs links is shifted to the left as compared to the other 3 links.

In terms of the dynamic thing, it's really fast. 1/20th of a second or something. I just see all the links shifted 1 or 2 characters to the right. It's a blur really. But it is definitely happening. I wish I could run the browser in slow motion to see what's happening exactly.

**Comment by geeknoid** [comment]
Could you put a few white pixels between the blue nav bar and the icon? It  looks a bit cramped at the moment.

**Comment by ryangrahamnc** [comment]
This is caused by the browser loading the css files and their includes asynchronously, which is something we cant control. The fonts are updated with a woff file that takes 1/20th of second longer to pull since its in a separate http request. This change is out of our control.
Additionally, I only see it on first pageload, or if I do a force refresh. Given many websites do the same thing, I dont think its worth fixing.

**Comment by davetropeano** [comment]
+1 to ryan's comments. Also, I don't always see the shift -- only on a clean cache will you notice it.

**Comment by geeknoid** [comment]
OK, that's too bad about the async stuff.

That just leaves the static shifting then I guess :-)

**Comment by geeknoid** [comment]
Guys, I believe you weren't quite on the mark about this one. There are two reasons for the shifting:

- The width of the logo in the nav bar was not explicitly specified. The browser assumed a width of zero, and rendered the Istio label first. When the image was loaded, it shifted the word Istio to the right to make room. Explicitly specifying the image with in the markup fixed this and Istio renders in the right spot to begin with.

- The top nav items shimmy left-right because of the scroll bar. When the nav bar is first rendered, the HTML for the page hasn't yet loaded so there isn't a scroll bar. As HTML is loaded and the true height is known, the scroll bar is drawn and the nav bar content (being right justified) shifts left. Clicking from link to link causes things to shift over and over again accordingly.

Is there a way to right justify somewhat independently on the scroll bar such that things don't move whether or not the scrollbar is there? Or maybe defer rendering the links in the nav bar until the decision to add or not the scrollbar has been made?

**Comment by geeknoid** [comment]
Fixed it....
