### ISSUE TITLE
rake test jenkins needs to run on all commits on master

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#299]
and comment when it breaks (so an email get sent to committer, and some trace shows up)

to avoid https://github.com/istio/istio.github.io/issues/298

**Comment by sebastienvas** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Slack+Plugin

**Comment by sakshigoel12** [comment]
@sebastienvas  how are we doing on this? Can we add an ETA

**Comment by sebastienvas** [comment]
We have a postsubmit, I am assuming this is done. @ldemailly  ?

**Comment by ldemailly** [comment]
it does run, yes, thanks (for instance https://testing.istio.io/job/istio.github.io/job/postsubmit/241/console )

but if it was to fail, who would get notified/notice ?

**Comment by sebastienvas** [comment]
Yes - let me add another issue for notification
