### ISSUE TITLE
Images on Community page are broken on mobile

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#304]
The various images on the Community page are squeezed down to a few pixels horizontally when viewed in portrait mode on a mobile device using Chrome.

**Comment by ldemailly** [comment]
I can file separate issue if you prefer but on mobile:
true-index.html is also a tiny bit too tall, the "An open..." paragraph is cut at the bottom and the down arrow doesn't show (btw I wonder if that down arrow should be a link that scrolls to the next segment of the page)
this is on a google pixel with chrome and iphone 7 plus on safari

**Comment by geeknoid** [comment]
Yes, separate issue please.

We're already making the down arrow into a clickable thing. Coming soon

**Comment by ldemailly** [comment]
I see #306 addresses my point, thanks
