### ISSUE TITLE
Shrink the width of the left nav

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#339]
The left nav is currently consuming 25% of the total width of the page. It's generally way too wide for its content. It's width should be set based on its content rather than being hardcoded to 25%.

**Comment by LisaFC** [comment]
Though if the width is based on the content will it not look like it's jumping backwards and forwards when you switch between sections?

**Comment by geeknoid** [comment]
Fair point. Maybe we should just reduce it to 20% instead of 25%...

**Comment by geeknoid** [comment]
Fixed by PR #826
