### ISSUE TITLE
Need to publish talks on the web site

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#342]
Options:

#1. Add an "In the News" section which is just a list of events with pointers to presentations, papers, videos.

#2. Add an "Istio Calendar" showing events in the past and future, with associated links to papers, presentations, videos. This tells people where we'll be in the future which is nice.

#3. Add a specific "Presentations" section which just had presentations and videos.

Or combinations of the above.

**Comment by douglas-reid** [comment]
Is this something @thisisnotapril can help with now? would be great to have at least the Calendar bits, especially as more and more events are popping up.
