### ISSUE TITLE
presubmit comments twice on each PRs

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#352]
e.g
https://github.com/istio/istio.github.io/pull/351
![screen shot 2017-05-26 at 2 44 02 pm](https://cloud.githubusercontent.com/assets/3664595/26513726/f10ba354-4221-11e7-8763-cfd0285b2967.png)
there was no rebase, the comments are seconds apart
not a huge deal but it's cosmetically wasting space and notifications/comments

**Comment by sakshigoel12** [comment]
I think this is fixed. @sebastienvas can you check?

**Comment by ldemailly** [comment]
it's not ( https://github.com/istio/istio.github.io/pull/602#issuecomment-334201530 for instance)
but it's also not very important - we should move this repo like all of the istio ones to prow though

**Comment by ldemailly** [comment]
fixed by switching to new presubmit
