### ISSUE TITLE
Issue with faq/index.md : URL should update for each question

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#356]
clicking on a question should update the URL with an anchor opening the faq question so it's easy to link that answer

past life example where that worked: http://quidscor.sourceforge.net/FAQ.html#name

**Comment by ldemailly** [comment]
Martin kindly started in #377

**Comment by geeknoid** [comment]
And I don't know how to go the next step.

[I guess I shouldn't admit that :-)]
