### ISSUE TITLE
Edits for the new color scheme

### ISSUE THREAD

**Issue by jasminejaksic** [istio/istio.github.io#36]
Refer to the staged site (http://istio-staging.surge.sh/):

1. When you scroll the home page, the old banner image becomes visible
<img width="1229" alt="screen shot 2017-04-19 at 1 53 19 pm" src="https://cloud.githubusercontent.com/assets/23645863/25202705/264e57ca-250b-11e7-85f4-f0692beeab3b.png">

2. The downward pointing arrow should be blue to match the overall color scheme
<img width="693" alt="screen shot 2017-04-19 at 1 53 36 pm" src="https://cloud.githubusercontent.com/assets/23645863/25202794/758d352c-250b-11e7-91f9-00bc67500562.png">

3. When you hover over the button, it switches to teal (should we change it to a different shade of blue?)
<img width="773" alt="screen shot 2017-04-19 at 1 53 51 pm" src="https://cloud.githubusercontent.com/assets/23645863/25202977/3ff41f88-250c-11e7-866e-95486a67c27f.png">

**Comment by ZackButcher** [comment]
Also I find the text of the buttons a bit hard to read: the text is very thin.
