### ISSUE TITLE
provide updatable snapshot of previous releases

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#367]
either a separate (virtual) host
releases.istio.io/v0.1
or under istio.io as a sub directory (could possibly be a submodule)

the goal is that there is a branch (like https://github.com/istio/istio.github.io/tree/release-0.1 ) or some otherway to easily update the snapshot of alpha docs (and ditto for 0.2 etc... later)

I tried to use forks (e.g. https://ldemailly.github.io/istio-0-1.github.io/ ) but it doesn't seem possible to fork inside the same org (I suppose we could create a istio-releases org but that seems heavy handed)

cc @mandarjog @ayj @geeknoid

**Comment by geeknoid** [comment]
I suggest the following:

- We create a branch in istio.github.io for every release.

- The active branch under development is called 'next'. The current release's branch is called 'current'.

- When a release takes place, the 'current' branch is renamed to its explicit version number (V0.1), the next branch is renamed to current, and a new next branch is created.

- We have an automated build process that takes all these branches, runs Jekyll for all of them, does whatever sed processing is necessary to patch URLs, and then dumps the resulting HTML into istio.github.io and checks that in as is. The versioned branches all get subdirectories, while the current branch is at the root.

  istio.github.io/ 
  istio.github.io/versions/V0.1
  istio.github.io/versions/next

This seems like a composition of simple steps.

**Comment by ldemailly** [comment]
simplification proposal: we probably only need docs.istio.io to point to the last release (aka alpha and the `release-0.1` branch for now) and istio.io to be current (`master`) and that's it for the next 3 months; after which we can also erase alpha docs and replace them by beta docs... we will only need to keep more than 1 after GA

And in `master` we add a link in the header to "0.1 release docs" and that's it

**Comment by ldemailly** [comment]
We're going to go with mandar's solution but for reference I got a very quick "github pages only, nothing else required" hack going with https://istio-releases.github.io/v0.1/docs/ by creating an org for releases and forking the site there

**Comment by geeknoid** [comment]
What  is Mandar's solution(tm) ?

**Comment by ldemailly** [comment]
> What is Mandar's solution(tm) ?

linked above:  #368

**Comment by ldemailly** [comment]
See also #406, #407 and #379

**Comment by ldemailly** [comment]
all done except the post submit on release-0.1 is failing
