### ISSUE TITLE
RBAC instructions insufficient for users without permission for default namespace

### ISSUE THREAD

**Issue by esnible** [istio/istio.github.io#372]
First, the file _install/kubernetes/istio-rbac-alpha.yaml_ explains "If deploying istio to a namespace other than 'default' then change the ClusterRoleBinding namspace target appropriately." but this instruction is not present in __docs/tasks/installing-istio.md_.  A colleague of mine was confused by this.

Second, "namspace" is mispelled in _install/kubernetes/istio-rbac-alpha.yaml_:8

**Comment by sakshigoel12** [comment]
@costinm how far are we on this?

**Comment by ldemailly** [comment]
this is resolved afaik
