### ISSUE TITLE
Publish versioned documentation sites on postsubmit

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.github.io#379]
`scripts/build.sh` builds and publishes the currently checked out version of the documentation site  to firebase with the specified prefix.

The version should be specified with the following mapping.
RELEASE should be specified as numbers only.
ex: RELEASE=0.1

@ayj We need to add mapping from

istio.io/v-${RELEASE} ---> https://istiodocs-v01.firebaseapp.com/v-${RELEASE}/

**Comment by ayj** [comment]
https://istio.io/v-0.1 is now mapped to https://istiodocs-v01.firebaseapp.com/v-0.1.

**Comment by ldemailly** [comment]
that dash isn't great (v0.1/ would be better than v-0.1/)

more importantly there shouldn't be a home page there - should go directly to docs/ ?

**Comment by ldemailly** [comment]
I just synced the release-0.1 branch before it diverges

we need
- [ ] add redirects etc so only docs/ is versioned
- [ ] add navigation to the 0.1 site from the main site and vice versa

any takers ? cc @geeknoid

**Comment by ldemailly** [comment]
Jason is working on the redirects and I did a super basic cross linking proposal with #406 and #407

**Comment by ldemailly** [comment]
for redirects we need:
/v-0.1/ -> /
/v-0.1/index.html -> /
And all those :
/about/
/blog/
/troubleshooting/ 
/faq/
/search/
/bugs/
/community/

all those with "*" at the end

specifically we shouldn't redirect docs/ (clearly) but also not img/ js/ etc... which may change on the main site

**Comment by ldemailly** [comment]
cool redirects in https://github.com/istio/admin-sites/pull/19 - thanks jason !

**Comment by ldemailly** [comment]
it's all in place, now we just need to automate the release-0.1 -> push (or not, as it shouldn't change that often anyway but it'd be cleaner) - ic https://github.com/istio/istio.github.io/pull/381 but it's not turned on ? @sebastienvas
