### ISSUE TITLE
Document the permissions required for each Istio component to work

### ISSUE THREAD

**Issue by ZackButcher** [istio/istio.github.io#389]
We have [RBAC files in istio/istio/install](https://github.com/istio/istio/blob/master/install/kubernetes/istio-rbac-beta.yaml) but it would improve discoverability and ease transporting Istio to new environments if we explicitly broke down the roles used by each Istio component and the permissions allowed by those roles.

@andraxylia @costinm @ldemailly wrote the RBAC rules AFAIK, thoughts?

**Comment by ldemailly** [comment]
I didn't sorry / no knowledge of RBAC (but agree on the portability issue)

**Comment by andraxylia** [comment]
Docs will be based on the outcome of:
istio/istio#341
istio/istio#343

**Comment by andraxylia** [comment]
The permissions will be in the RBAC rules themselves, which are readable. The permissions are related to the code and should not be documented separately.
