### ISSUE TITLE
Adding Details of Sidecar Arguments

### ISSUE THREAD

**Issue by kameshsampath** [istio/istio.github.io#401]
Cases where the users prefer to do a template includes or use spec generated out of kube-inject as part of other CI/CD tool, he need to understand more details on the Init Containers/Sidecar proxies and its arguments.

**Comment by rshriram** [comment]
cc @ayj 
Can you take a stab at this? This would probably go into the installing sidecar section.

**Comment by ayj** [comment]
Sure thing. I'll work on it this week.

**Comment by rshriram** [comment]
fixed..
