### ISSUE TITLE
Typo on MUTUAL_TLS (missing underscore in documentation

### ISSUE THREAD

**Issue by dbenque** [istio/istio.github.io#402]
The AuthPolicy enum documentation is missing the underscore for the value MUTUAL_TLS.

https://istio.io/docs/reference/config/service-mesh.html#istio.proxy.v1.config.ProxyMeshConfig.AuthPolicy

Fix to be done in here: https://github.com/search?q=org%3Aistio+MUTUALTLS&type=Code

According to protobuf definition, and underscore is needed:
https://github.com/istio/api/blob/9c20ee79d087ccb53d3f824ece0b0e9e90f21d51/proxy/v1/config/proxy_mesh.proto#L112

**Comment by geeknoid** [comment]
Shriram, can this issue be closed?
