### ISSUE TITLE
"istioctl kube-inject" link returns 404

### ISSUE THREAD

**Issue by tkhm** [istio/istio.github.io#421]
I found the link on installation guide returns 404.

"istioctl kube-inject" link on [istio.github.io/installing-istio.md at master · istio/istio.github.io · GitHub](https://github.com/istio/istio.github.io/blob/master/_docs/tasks/installing-istio.md) is currently returns 404.

The link address is https://github.com/istio/istio.github.io/blob/master/_docs/tasks/%7B%7Bhome%7D%7D/docs/reference/commands/istioctl.html#istioctl-kube-inject

And it should be https://github.com/istio/istio.github.io/blob/master/_docs/reference/commands/istioctl.md#istioctl-kube-inject

**Comment by ldemailly** [comment]
the .md in the istio.github.io aren't exactly meant to work out of the box when seen on github, they get processed by jekyll (which understands {{home}}) and pushed to istio.io, for instance
https://istio.io/docs/tasks/installing-istio.html#deploy-your-application
doesn't have any broken links
