### ISSUE TITLE
Create a task for using Mixer's IP List Checker to enforce IP based access controls

### ISSUE THREAD

**Issue by ZackButcher** [istio/istio.github.io#425]
We have an IP list checker adapter in Mixer, but we have no examples anywhere of using it. This would make a great Task.

**Comment by kyessenov** [comment]
Is this related to TCP filter and NetworkPolicy?

**Comment by ZackButcher** [comment]
Not really - during a Check call you can use this adapter to check that an IP expression (e.g. `source.ip`, `origin.ip`) is in a set of CIDR blocks. Someone on Twitter asked if Istio could do IP whitelist based rules, I looked around and found that we had no examples, even though it can.

**Comment by kyessenov** [comment]
This is precisely what NetworkPolicy does. We should try to align this with existing interest in that area, since it'll come up anyways.

**Comment by geeknoid** [comment]
Covered by #570
