### ISSUE TITLE
consider adding (social) comments plugin to the site

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#427]
it's fairly easy to add disqus or facebook comments and would be useful for blog posts at minimum
(I did it for my personal site with jekyll so if we decide to do it I can get it done)

cc @thisisnotapril

**Comment by ldemailly** [comment]
if you want some tips for setup:

https://laurentsv.com/blog/2017/08/06/comments.html

**Comment by geeknoid** [comment]
Steering committee decided against this.
