### ISSUE TITLE
Issue with _docs/tasks/istio-auth.md

### ISSUE THREAD

**Issue by ilyash** [istio/istio.github.io#430]
Hi.

The doc says:
`kubectl exec -it productpage-v1-4184313719-5mxjc -c istio-proxy /bin/bash `

It is probably outdated as what worked for me was
`kubectl exec -it productpage-v1-4184313719-5mxjc -c proxy /bin/bash `

More info:
Istio 0.1.6
Inject command returns YAML with container with `name: proxy`, not `name: istio-proxy`

**Comment by gyliu513** [comment]
@ilyash Please test with v0.1 document here https://istio.io/v-0.1/docs/tasks/istio-auth.html , this document is using `proxy`.

**Comment by gyliu513** [comment]
@ilyash I will close this one, feel free to contact me if you have any other questions. Thanks!

**Comment by ilyash** [comment]
I see. Worth considering: showing product version related to documentation in more prominent place (currently footer).

**Comment by gyliu513** [comment]
@ilyash you can probably file another issue to trace it if want to fix ;-)
