### ISSUE TITLE
istio installation using NodePort for some services

### ISSUE THREAD

**Issue by gyliu513** [istio/istio.github.io#439]
In https://github.com/istio/istio.github.io/blob/master/_docs/tasks/installing-istio.md#verifying-the-installation , we are using `NodePort` to check all of the services, but actually, all of the services in istio are not using `NodePort` but `ClusterIP`.

**Comment by ldemailly** [comment]
the current page (https://istio.io/docs/setup/install-kubernetes.html#verifying-the-installation )
only mentions nodeport in the text, as far as I can see it seems fine

@gyliu513 reopen with a specific detail if you still think it is a problem ? (screenshot + red annotation ideally)

**Comment by gyliu513** [comment]
@ldemailly you may see that neither of the services here https://github.com/istio/istio/blob/master/install/kubernetes/istio.yaml are created as NodePort, so I do not think that we can use NodePort in the output of `kubectl get svc`, comments?

**Comment by andraxylia** [comment]
The comment about NodePort relates to the Ingress, which has to be at least NodePort if not LoadBalancer. The rest of the svc are Cluster IP indeed, but I still do not see any problem. I will update the installation page today anyway, will assign you as reviewer as well.

**Comment by gyliu513** [comment]
Thanks @andraxylia @ldemailly I mean that we should not expose `NodePort` info in the output of `kubctl get svc` if we are not using `NodePort` for those services, such as Prometheus etc.
