### ISSUE TITLE
Docker command for running website locally does not work on Mac/Linux

### ISSUE THREAD

**Issue by GregHanson** [istio/istio.github.io#446]
From the main README:
```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll  -it -p 127.0.0.1:4000:4000 jekyll/jekyll jekyll serve
```
results in the following error:
```
Could not find minitest-5.10.2 in any of the sources
Run `bundle install` to install missing gems.
```
Running `bundle install` and even `gem install minitest -v 5.10.2` on linux and mac results in the same error the next time you try to run the docker command.

The mac steps at the end of the doc work fine for me so I believe this isn't an issue with ruby version or  the like.  Possible the issue is something in the jekyll image changed and it no longer includes minitest by default

**Comment by ldemailly** [comment]
this is the image I have and that works for me:

jekyll/jekyll                             latest                                     sha256:79ce56e2dc1990c2b630eeed5b1d7f494f31adc3bfddfb63e44c4719a1773c1d   sha256:bba35fc0824d1fc1ec178756f42672f118bbb793a79195e9a4a509f4bcef848f   4 months ago        275MB

as a data point, does that one work for you ?
(it's odd it works for me and CI but maybe it's caching)

**Comment by ldemailly** [comment]
this works
```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll  -it -p 127.0.0.1:4000:4000 jekyll/jekyll sh -c "bundle install; jekyll serve"
```

**Comment by GregHanson** [comment]
@ldemailly what env are you running the command in? mac/linux/windows?

**Comment by ldemailly** [comment]
the new instructions should work for you now too no ?

**Comment by GregHanson** [comment]
sorry, missed the updated command - yes it works now
