### ISSUE TITLE
Update Concepts on the website

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#449]
@sakshigoel12 commented on [Wed Sep 13 2017](https://github.com/istio/istio/issues/788)

**Comment by jasminejaksic** [comment]
What specifically is still pending and what's the ETA?

**Comment by geeknoid** [comment]
I've checked the general conceptual overview and the Mixer material and all that is up to date for 0.2. Someone should give the traffic management stuff a once over as well as the auth section.

**Comment by jasminejaksic** [comment]
@wattli is going to run through Auth and clean it up. 
@rshriram can you review traffic management section?

**Comment by rshriram** [comment]
Traffic management has been updated. Auth was also updated, but might need a cleanup

**Comment by sakshigoel12** [comment]
@wattli  confirmed security is good.
