### ISSUE TITLE
Create separate metrics task

### ISSUE THREAD

**Issue by rshriram** [istio/istio.github.io#459]
The sample page is bloated. It has lengthy content about grafana, service graph, zipkin, etc., which does not really fit in the sample page. It would be good to move them into a dedicated metrics task, where we explain the concepts and the setup to end users.

**Comment by douglas-reid** [comment]
I have a PR out that consists of some of initial content for this doc.  PTaL: https://github.com/istio/istio.github.io/pull/524

Once the base content is in, i will follow-up with a polish run.

**Comment by mandarjog** [comment]
The linked is already merged.

**Comment by sakshigoel12** [comment]
@douglas-reid @ZackButcher  please could you add an ETA
