### ISSUE TITLE
Need a dedicated Setup tab

### ISSUE THREAD

**Issue by rshriram** [istio/istio.github.io#460]
Our install options are increasing for both the control plane and the data plane. Need to move them into a separate Setup tab, where we can have a 
1. Quick Start Kubernetes (install control plane, data plane (sidecars in pods/vms), add ons)
2. Quick Start Consul (install control plane, data plane methodology, etc.)
3. Production Installation
    1. Kubernetes
        1. Install control plane components, with detailed explanations on turning off components
        2. Sidecar installation options (kube-inject, manually adding envoy container, initializer)
        3. Increasing performance of control plane (multiple pilots, mixers, etc.)
    2. Other environments (will be expanded in future)
         1. Control plane installation
         2. Sidecar integration options (docker, debian packages, etc.)

We can adopt some patterns from https://kubernetes.io/docs/setup/

**Comment by rshriram** [comment]
fixed by #465

**Comment by rshriram** [comment]
cc @SueGraham @Rachel-Graham

**Comment by ldemailly** [comment]
thanks for getting this done
