### ISSUE TITLE
Add Helm chart based install into the docs

### ISSUE THREAD

**Issue by rshriram** [istio/istio.github.io#462]
Need to add a Helm chart based install section in our installation task (also have to test and update the relevant helm charts).

cc @gyliu513 / @lachie83 would you like to take a crack at this?

I wonder if the bookinfo demo can be helm-fied.. Apologize if this is a supremely dumb thought in the world of helms.

**Comment by gyliu513** [comment]
@rshriram I already updated the installation guide for installing istio with helm chart here https://github.com/istio/istio.github.io/pull/413 and this PR was merged.

+1 to have the bookInfo as helm char, but we may need to add dependency that the bookInfo chart need to depend on istio chart. @lachie83 comments for this?

**Comment by linsun** [comment]
for bookinfo helm chart, what would be our recommendation for the review service v1/v2/v3?   would this be 3 charts but multiple versions?

**Comment by gyliu513** [comment]
@linsun I want to create one chart like this https://github.com/istio/istio/blob/master/samples/apps/bookinfo/bookinfo.yaml , it will include all of the three versions, then end user can just use some route control policies to adjust, comments?

**Comment by linsun** [comment]
@gyliu513 is it a common practice to put 3 versions of a given service in one helm chart?  That is what I was wondering.  I understand you could put all 3 versions in one chart, was trying to understand if that is common practice.

**Comment by rshriram** [comment]
Okay, since we already have a helm chart, I am closing this issue. We can discuss bookinfo in a separate issue.

**Comment by gyliu513** [comment]
@linsun The helm chart itself can handle different versions in one chart and end user can select the version that they want to deploy. But for bookInfo, as we need to run all of the three versions at one time for some test, such as traffic control etc, so putting all of the three versions in one chart maybe better?

**Comment by linsun** [comment]
I think that is a not a great way showing bookinfo in helm charts as it is not using common helm practice. with that, I'd prefer to delay that work till we have a good strategy and recommendation for samples with helm charts.

**Comment by gyliu513** [comment]
I think it is ok as long as we can guide customer set up the bookinfo with istio for test. ;-)

**Comment by ldemailly** [comment]
> Okay, since we already have a helm chart, I am closing this issue. We can discuss bookinfo in a separate issue.

we don't have helm charts for 0.2 yet and probably initially we will remove that pointer until someone has time to look into updating helm for 0.2 (but I don't think it's a priority as I only saw user errors from helm installs so far and not really benefits (though in fairness we'd need to track the success people have with helm too not just the issues))

**Comment by gyliu513** [comment]
I have filed an issue here https://github.com/kubernetes/charts/issues/1909 to trace it, will update the helm chart to 0.2 after istio 0.2 released. @ldemailly

**Comment by gyliu513** [comment]
Keep this open and I will fixe it after kubernetes/charts#1909 got merged @rshriram @ldemailly

**Comment by sdake** [comment]
@gyliu513  would you mind closing?  I think we have a good Helm approach now and master of this repo documents the helm chart.  Although the Helm chart documentation is outdated, I am shortly submitting a PR to update the contents.

RE bookinfo, not certain the best way to demonstrate that via a helm chart.  I think the `helm template`/`updateVersion.sh` removal effort has taught us it takes alot of work to unify around helm as a templating engine which is worth it for the main Istio manifests.  Unclear if the pain is worth the gain for bookinfo given the current schedule.  Perhaps post 1.0?

**Comment by ldemailly** [comment]
@vadimeisenbergibm was looking at bookinfo restructuring I think

**Comment by sdake** [comment]
Helm update issue tracker: https://github.com/istio/istio.github.io/issues/1113
