### ISSUE TITLE
Track manual edits to generated docs

### ISSUE THREAD

**Issue by ZackButcher** [istio/istio.github.io#464]
Nearly all of the content in the reference section of the site is automatically generated, much of it from the protos in https://github.com/istio/api. This issue tracks the categories of manual edits we made to the 0.1 version of the generated docs so we can ensure we do the same to the next round of generated docs for the 0.2 version.

Assigned a smattering of people I know did manual updates.

**Comment by douglas-reid** [comment]
I definitely have added a bunch of manual edits to the Mixer bits, including:
- pulling out ValueType from template docs into a single place
- cleaning up junk from the generated config doc
- adding a manifests and a rules doc
- fixing enum values.

**Comment by geeknoid** [comment]
All right gang, is this still a useful bug?

I'm going to open a separate issue to track the fact we need to fully automated reference doc production and avoid this messiness moving forward.

**Comment by rshriram** [comment]
This isn’t a bug. More like a log so that we replay the actions every time
we manually  generate docs. That tool could be automated but it’s of not
much use as there are lots of manual cleanups/post processing. After that
tool is open sourced, we need to fix all of this before settling into
permanent automatic doc gen.

**Comment by rshriram** [comment]
Cleaned up routing protos: 
1. reorganized section order to flow top to bottom (concepts first),
2. removed unnecessary anchors, sections that shouldn’t be documented,
3. *added underscores to enum fields that doc gen stripped*, 
4. put misplaced doc sections (fault filter) into the correct page.

**Comment by rshriram** [comment]
These were done for 0.2 as well.

**Comment by kyessenov** [comment]
closing since we have a new fancy proto doc tool
