### ISSUE TITLE
validation (presubmit and for developers ) is slow, we should make an image

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#466]
@ldemailly commented on [Sat Sep 16 2017](https://github.com/istio/istio/issues/839)

we should make a docker with jekyll + bundle install to save a lot of time when validating or serving the website

---

@ldemailly commented on [Mon Sep 18 2017](https://github.com/istio/istio/issues/839#issuecomment-330365011)

sorry I filled this in the wrong repo, moving it

**Comment by ldemailly** [comment]
I found that github pages currently uses 3.5.2 (#491)
will build a docker too

**Comment by geeknoid** [comment]
I think we have this now, right? Can we close this issue?

**Comment by ldemailly** [comment]
yup, I think it's finally mostly working
