### ISSUE TITLE
Integrating other service registry. Using consul, eureka with Istio

### ISSUE THREAD

**Issue by rshriram** [istio/istio.github.io#469]
@sakshigoel12 commented on [Wed Sep 13 2017](https://github.com/istio/istio/issues/767)

---

@linsun commented on [Wed Sep 13 2017](https://github.com/istio/istio/issues/767#issuecomment-329164198)

Part of this is done in #681.  cc @ijsnellf would like to have similar docs for Eureka.

---

@rshriram commented on [Wed Sep 13 2017](https://github.com/istio/istio/issues/767#issuecomment-329320111)

@linsun this is for the istio docs tasks. 
cc @GregHanson

**Comment by geeknoid** [comment]
Can we close this? We seem to have doc coverage in those areas now.

**Comment by geeknoid** [comment]
We have this.
