### ISSUE TITLE
bookinfo.md contains unclear instructions on setting up Grafana

### ISSUE THREAD

**Issue by esnible** [istio/istio.github.io#49]
The current instructions are too difficult.  They expect the user to know the grafana-svc-external-IP.  They expect the user to understand how to change the Service from type LoadBalancer to type NodePort and under what circumstances that is needed.  They expect the user to know how to run `kubectl proxy` and how to edit Grafana's Istio-dashboard.

**Comment by douglas-reid** [comment]
@esnible how does the following sound:

- simplify the instructions for getting grafana IP address configured
- eliminate any mention of using NodePort (assuming that if you want to do that, you'll know what that means)

?

**Comment by esnible** [comment]
Good enough for me!
