### ISSUE TITLE
Doc: Distributed Tracing Task - Jaeger Setup

### ISSUE THREAD

**Issue by ZackButcher** [istio/istio.github.io#537]
@bismarck commented on [Mon Sep 25 2017](https://github.com/istio/issues/issues/73)

**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.2.4
GitRevision: 9c7c291eab0a522f8033decd0f5b031f5ed0e126
GitBranch: master
User: root@822a7ac3ca86
GolangVersion: go1.8.3
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
Yes
**What happened**:
In order to install Jaeger, the instructions ask you to run
```
kubectl apply -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml
```
This installs Jaeger in your current namespace and no spans are collected.
**What you expected to happen:**
Jaeger should be installed in the istio-system namespace.  The instructions should be changed to
```
kubectl apply -n istio-system -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml
```
**How to reproduce it:**
Follow the directions on https://istio.io/docs/tasks/telemetry/distributed-tracing.html to install Jaeger.

**Comment by rshriram** [comment]
fixed.
