### ISSUE TITLE
Doc: improve text formatting in Security > Testing Istio Auth

### ISSUE THREAD

**Issue by ZackButcher** [istio/istio.github.io#538]
@lgfa29 commented on [Mon Sep 25 2017](https://github.com/istio/issues/issues/74)

**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
$ istioctl version
Version: 0.2.4
GitRevision: 9c7c291eab0a522f8033decd0f5b031f5ed0e126
GitBranch: master
User: root@822a7ac3ca86
GolangVersion: go1.8.3


$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d
97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d
97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?** Yes

**What happened**:
The last section of the [Testing Istio Auth](https://istio.io/docs/tasks/security/istio-auth.html#testing-istio-auth) page seems to be missing some formatting to make the text easier to read. 

For example, it's missing the use of `<code>` tags in some words like `productpage`, `-k`, `cert-chain.pem`.

It also references `Envoy` with lower case `e`, whereas everywhere else uses uppercase.

It would also be nice to have a **What’s next** section like other tasks do because the final goal of this task was not very clear to me.

**Comment by ldemailly** [comment]
this was fixed recently afaik
