### ISSUE TITLE
yaml references to distributed files should be clickable

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#567]
for instance when looking at
https://istio.io/docs/tasks/traffic-management/traffic-shifting.html

telling the user to
istioctl create -f samples/bookinfo/kube/route-rule-all-v1.yaml
yet having no easy way to just peek at what is in that file is not as helpful as it could be

**Comment by geeknoid** [comment]
Could we create some linting thing to detect these references so we get told?

**Comment by ldemailly** [comment]
I think creating a new tag for references into our source tree would be good

also we should enforce that people use a tag and not master so they don't keep breaking when we move files around (or we should stop moving files around)

**Comment by geeknoid** [comment]
We could also show the file contents upon hovering over the link.

**Comment by ldemailly** [comment]
hover may be a lot of downloads but click could pop up the content yes

**Comment by ldemailly** [comment]
unless we would fetch the content at build time, that would avoid  also 404s when file move after the site is built
