### ISSUE TITLE
retry-injection task

### ISSUE THREAD

**Issue by esnible** [istio/istio.github.io#57]
I have created documentation for a retry task.  It is very similar to the fault injection task in structure.  However, to get it to demonstrate a successful recovery using retry I had to create a custom image.

The reason I created a custom image was to have a repeatable sequence of HTTP failures followed by success so that I could show HTTP retries leading to success.  With my custom server I can demonstrate the same URL returning 500, then another 500, then a 200, like this:

```
docker run -d -p 127.0.0.1:8080:8080 toxique
$ curl -i localhost:8080/hostname?codes=500,500,200
HTTP/1.1 500 Internal Server Error
92a8f2ebe4e7
$ curl -i localhost:8080/hostname?codes=500,500,200
HTTP/1.1 500 Internal Server Error
92a8f2ebe4e7
$ curl -i localhost:8080/hostname?codes=500,500,200
HTTP/1.1 200 OK
92a8f2ebe4e7
```

I am not sure if the Istio project wants this code (it's 100 lines of Go) and what I need to do to contribute it.  Without a server that can return failure then success on the same URL I can still document the steps to adding HTTP retries with Istio but I can't demonstrate to the user that Istio is correctly performing the retries.

**Comment by geeknoid** [comment]
Andra, can you help Ed figure out the right strategy?

**Comment by rshriram** [comment]
Our docs cover setup for retries and circuit breakers. We need to demonstrate retries with budgets.

**Comment by rshriram** [comment]
Closing this for now. We need to revisit this later
