### ISSUE TITLE
Issue with _docs/tasks/traffic-management/request-routing.md

### ISSUE THREAD

**Issue by alamba3890** [istio/istio.github.io#590]
Content-based routing: Under point 1., there is a typo in the command to display the routes.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/15128587/31095795-08bb0faa-a788-11e7-8863-5ded17083177.png">

The correct command is `istioctl get route-rules -o yaml`

**Comment by gyliu513** [comment]
```
[root@ib17b01 istio-0.2.6]# ./bin/istioctl get route-rules
Usage:
  istioctl get <type> [<name>] [flags]

Examples:

		# List all route rules
		istioctl get routerules

		# List all destination policies
		istioctl get destinationpolicies

		# Get a specific rule named productpage-default
		istioctl get routerule productpage-default
```

`istioctl get route-rules` is going to be deprecated, we recommend using `routerules` instead.
