### ISSUE TITLE
mesh-expansion instruction nit's

### ISSUE THREAD

**Issue by saumoh** [istio/istio.github.io#600]
In the page: https://istio.io/docs/setup/kubernetes/mesh-expansion.html

Section: "Preparing the Kubernetes cluster for expansion"
Ref to setupMeshEx should be: setupMeshEx.sh
install/tools/setupMeshEx initCluster
should be:
install/tools/setupMeshEx.sh initCluster

Section: "Setting up the machines"
Bullet: "Install Istio Debian files and start ‘istio’ and ‘istio-auth-node-agent’ services."
the instruction 'dpkg -i ..." references .deb that are not there. That seems to be a typo.
for example:  dpkg -i ${ISTIO_STAGING}/istio-proxy-envoy.deb
should be:     dpkg -i ${ISTIO_STAGING}/istio-proxy-release.deb

**Comment by rcurran1** [comment]
Update requested for ""Preparing the Kubernetes cluster for expansion" section was made in commit;
commit fd7a95517bf91a5f9ba9bcdb7cb94dcfa09a6a5f, Author: Laurent Demailly <ldemailly@gmail.com>, Date:   Thu Oct 12 18:46:49 2017 -0700

Update to 'Section: "Setting up the machines"' was not made, perhaps intentionally.

**Comment by linsun** [comment]
Perhaps you meant @ldemailly ?

**Comment by ldemailly** [comment]
didn't see this issue but I fixed those a while ago
