### ISSUE TITLE
Images captions are wrong in Distributed Tracing task

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio.github.io#608]
![image](https://user-images.githubusercontent.com/19473346/31198376-b18c381a-a919-11e7-8447-03ed639a6165.png)

https://istio.io/docs/tasks/telemetry/distributed-tracing.html

**Comment by ayj** [comment]
The images are also really tiny and hard to read unless I open in a new tab. And the notion of _left_ and _right_ is not correct (they're vertically stacked in the pic above and on my screen).

**Comment by bingoarun** [comment]
This bug can be closed.

**Comment by ldemailly** [comment]
Pro tip, next time put just "fixes #608" (without 'bug') and it will automatically close on merge
