### ISSUE TITLE
Ingress path matching syntax not documented.

### ISSUE THREAD

**Issue by frankbu** [istio/istio.github.io#615]
We need to document the regex vs. prefix vs. exact match syntax in ingress paths.

Currently, `/` will map to the exact match `/`. `anything.*` maps to prefix match for prefix `anything` and any other use of regex chars (`.`, `*`, etc.) is mapped to a regex match. So, for example, `/*` maps to the regex for zero or more `/` chars.

Are we planning to change this implementation? If so, we should also open an issue in pilot and do that first.

**Comment by linsun** [comment]
not sure we 'll have time for this for 0.2.x since we may likely ship 0.2.7...would be good to have a doc for this.

**Comment by frankbu** [comment]
@linsun I agree that changing the implementation is for 0.3.

**Comment by geeknoid** [comment]
Has this been addressed?

**Comment by ldemailly** [comment]
there is no regex support afaik

**Comment by frankbu** [comment]
We've ended up simplifying ingress (removed the regex cleverness), and are planning to use the new Gateway/RouteRules in v1alpha2 to do the more advanced things. I think we still need to document the behavior of Istio Ingress, and also mention that Gateway is the recommended way to define the ingress in istio, once that's working.

**Comment by blaketastic2** [comment]
@frankbu You mentioned some documentation. Is this started/ready somewhere? If not, any thoughts on where I can dig into code to start getting something together on this?

**Comment by frankbu** [comment]
@blaketastic2 The documentation is still a WIP but you can look at the APIs here: https://github.com/istio/api/tree/master/networking/v1alpha3

The `v1alpha3` model is mostly working, but there are still some bugs and incomplete functionality, esp. with the Gateway.

Updated Bookinfo sample rules (mostly working) in this branch: https://github.com/istio/istio/tree/v1alpha3-routing/samples/bookinfo/routing-rules

Updated Tasks documentation (ingress/gateway task not converted yet): https://github.com/istio/istio.github.io/tree/v1alpha3-routing/_docs/tasks/traffic-management

**Comment by rshriram** [comment]
No. Let’s close this.
