### ISSUE TITLE
Request Timeout Task mentions erroneous delay

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.github.io#620]
https://istio.io/docs/tasks/traffic-management/request-timeouts.html

In step 5, the current text reads: `You should now see that it returns in 1 second (instead of 2), but the reviews are unavailable.`

When tested, I observed that the result returns in 2 secs still. The reviews were not shown (correctly) and a proper message was generated on the page. However, timing the page load demonstrated that the fixed delay of 2s was still observed.

I did note a slight speed-up however (presumably savings from the timeout).

**Comment by rshriram** [comment]
Can you confirm that the timeout works though? May be set a 6 second delay and a 3 second timeout.

**Comment by douglas-reid** [comment]
The timeout was working.

When I set the delay to <1s, everything returned fully. Any value >1s showed the expected results of a timeout, just not a reduction in response time.

**Comment by geeknoid** [comment]
Is this bug still relevant?
