### ISSUE TITLE
"Access control using whitelists" subtask needs verification action

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.github.io#624]
https://istio.io/docs/tasks/security/basic-access-control.html

Once the config is created, there should be some small section on validation -- even if it only involves telling users to delete the old deny rule and repeat the v3 validation bits again. It isn't clear what observable effect users should expect.

This may, in part, be because the text: 

>We would like to cut off access to version v3 of the reviews service.

lives inside of the other subtask and not at a higher level.

**Comment by frankbu** [comment]
FIxed in https://github.com/istio/istio.github.io/pull/639
