### ISSUE TITLE
Suggestions for docs/tasks/telemetry/tcp-metrics.html

### ISSUE THREAD

**Issue by ayj** [istio/istio.github.io#633]
* configuration in this step uses `default` vs. `istio-system` elsewhere. Even though both are correct it might be good to be consistent for first time users to avoid introducing unnecessary concepts.

* Formatting of the code in step #1 is wrong. There is a leading column space in the entire file that needs to be removed and `name`and `namespace` need to be indented.

* Steps 3.1 and 3.2 assumes manual injection with `kube-inject`. It needs to be updated for initializer case similar to https://istio.io/docs/guides/bookinfo.html#running-on-kubernetes

* Step #3.3 uses `kubectl` instead of `istioctl`. This isn't consistent with other tasks which use `istioctl` for istio configuration.

* The Promethes UI link to `mongo_received_bytes` metric doesn't show anything

![screenshot from 2017-10-05 16 05 48](https://user-images.githubusercontent.com/116378/31256397-18eb3dee-a9e7-11e7-9c95-873991f9e458.png)
 
* _Cleanup_ is missing a step to stop the port-forwarding to the pod, e.g. `killall kubectl`

**Comment by douglas-reid** [comment]
Closing this issue after update. I believe everything has been addressed. If not, this should be re-opened.
