### ISSUE TITLE
Suggestions for docs/tasks/telemetry/querying-metrics.html

### ISSUE THREAD

**Issue by ayj** [istio/istio.github.io#634]
* It seems like this task should appear _before_ 
[docs/tasks/telemetry/metrics-logs.html](https://istio.io/docs/tasks/telemetry/metrics-logs.html) and [docs/tasks/telemetry/tcp-metrics.html](https://istio.io/docs/tasks/telemetry/tcp-metrics.html) in the sidebar. It covers the basic concept of Prometheus and how it integrates with Mixer using the default Mixer config without introducing the more complex rules, e.g. [docs/tasks/telemetry/metrics-logs.html#understanding-the-metrics-configuration](https://istio.io/docs/tasks/telemetry/metrics-logs.html#understanding-the-metrics-configuration)

* _Cleanup_ is missing a step to stop the port-forwarding to the pod, e.g. `killall kubectl`

**Comment by douglas-reid** [comment]
I'm of two minds on this. Prometheus isn't a core Istio integration. It is the "default" (for lack of a better word) Mixer adapter for metrics. However, using Prometheus (and understanding how to query it, etc.) isn't strictly part of the Istio metrics experience.

I'm leaning towards leaving the ordering as-is, with core tasks of collecting above querying via add-ons.

Thoughts?
