### ISSUE TITLE
.svgs in request routing ingress/egress doc are not rendering

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio.github.io#642]
The svgs here are not rending for me (Firefox 56.0):
https://istio.io/docs/concepts/traffic-management/request-routing.html#ingress-and-egress

**Comment by linsun** [comment]
I saw the same in safari

**Comment by rshriram** [comment]
Thanks for spotting this. Will fix

**Comment by rshriram** [comment]
fixed
