### ISSUE TITLE
mixer status code is not linked to the reference doc

### ISSUE THREAD

**Issue by ayj** [istio/istio.github.io#653]
@saturnism commented on [Sat Oct 07 2017](https://github.com/istio/issues/issues/91)

**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Yes

**Bug:** Y

**What happened**:
In [Istio / Status RPC](https://istio.io/docs/reference/api/mixer/status.html#google.rpc.Status.details), in the field table, `google.rpc.Code` is not linked to the actual code. `google.rpc.Status.details` link does not work. 

**What you expected to happen:**
When referencing external values (such as gRPC codes), doc should be linked.

**How to reproduce it:**

**Feature Request:**
Y/N

**Describe the feature:**

---

@linsun commented on [Mon Oct 09 2017](https://github.com/istio/issues/issues/91#issuecomment-335276809)

Thanks for reporting this, a PR is welcomed!

**Comment by ayj** [comment]
/cc @geeknoid @ldemailly 

We're not generating docs for the expected target link (https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto).

**Comment by ldemailly** [comment]
this happened in 0.1 already but I forgot how we fixed it (maybe by hand?)
I'm surprised bad links made it through despite the rake test ?

**Comment by ayj** [comment]
https://istio.io/docs/reference/api/mixer/status.html#google.rpc.Status.details is a valid link in the sense that it returns 200.

**Comment by ldemailly** [comment]
the anchor exists and it goes there for the above link <a name="google.rpc.Status.details">

so is the bug that it links to itself ? does it work for other types ? is there an html page for https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto ?

**Comment by ayj** [comment]
Looks like https://cloud.google.com/appengine/docs/admin-api/reference/rpc/google.rpc#google.rpc.Status has the same behavior. The reflink is to the table at the bottom of the page which is not obvious if the window is maximized.
