### ISSUE TITLE
Istio Ingress Controller Page error

### ISSUE THREAD

**Issue by wattli** [istio/istio.github.io#672]
https://istio.io/docs/tasks/traffic-management/ingress.html

In this page, we have a input box to deploy 'deny-route' rule [right below "This configuration above will allow access to all URIs in the httpbin service."]

There are leading spaces in that input box, and copy/paste will give you errors (the input box above does not have this issue).

Then i remove these leading spaces, I still got another error: 

Error: configuration is invalid: 1 error occurred:
* name or service is mandatory for a service reference

Not sure who is the right person to assign to. But please fix, this does not seem hard but it would block our customers from trying out this feature.

**Comment by ldemailly** [comment]
Screenshot? Which section / link from TOC and copy paste the url ? I don't see it (on my phone)

**Comment by geeknoid** [comment]
I see the problem. I'll get a fix together by tomorrow.

**Comment by wattli** [comment]
@ldemailly , do you know how to paste a screenshot? I don't see an option to upload an image. I can provide a screenshot with internal tool, but that's google only :(

**Comment by ldemailly** [comment]
drag and drop

**Comment by geeknoid** [comment]
The formatting issues have been resolved.

Content-related issues need to be tackled by someone else

**Comment by wattli** [comment]
<img width="575" alt="screen shot 2017-10-19 at 10 16 13 am" src="https://user-images.githubusercontent.com/24381542/31784465-995ff03a-b4b6-11e7-9515-5d0f486dd78b.png">

**Comment by wattli** [comment]
@rshriram @ldemailly @mandarjog 
Do you guys know who is the right person for this bug shown in the screenshot above?

**Comment by linsun** [comment]
I was able to recreate this, however I by passed this using kubectl:

➜ linsun@Lins-MacBook-Pro  ~/go/src/github.com/linsun/istio-ingress/plans git:(master) ✗ cat <<EOF | istioctl create -f -
## Deny all access from istio-ingress
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: deny-route
spec:
  destination:
    name: httpbin
  match:
    # Limit this rule to istio ingress pods only
    source:
      labels:
        istio: ingress
  precedence: 1
  route:
  - weight: 100
  httpFault:
    abort:
      percent: 100
      httpStatus: 403 #Forbidden for all URLs
EOF

Error: configuration is invalid: 1 error occurred:

* name or service is mandatory for a service reference
➜ linsun@Lins-MacBook-Pro  ~/go/src/github.com/linsun/istio-ingress/plans git:(master) ✗ cat <<EOF | kubectl create -f -
## Deny all access from istio-ingress
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: deny-route
spec:
  destination:
    name: httpbin
  match:
    # Limit this rule to istio ingress pods only
    source:
      labels:
        istio: ingress
  precedence: 1
  route:
  - weight: 100
  httpFault:
    abort:
      percent: 100
      httpStatus: 403 #Forbidden for all URLs
EOF

routerule "deny-route" created

**Comment by linsun** [comment]
created a PR to update doc to use kubectl.  We can use this to investigate why istioctl doesn't work.  https://github.com/istio/istio.github.io/pull/678

**Comment by juliaaano** [comment]
I would like to remind that even if this documentation issue gets resolved, this "deny-route" might still not work: https://groups.google.com/forum/?#!msg/istio-users/PLhWfWMv_Bo/y1GJ3nPlBQAJ

**Comment by linsun** [comment]
ok with the doc fix, the route deny is mostly working:


Lins-MacBook-Pro:httpbin linsun$ curl -I http://169.60.77.242/headers
HTTP/1.1 200 OK
server: envoy
date: Fri, 20 Oct 2017 15:31:47 GMT
content-type: application/json
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 523
x-envoy-upstream-service-time: 9
Connection: Keep-Alive

Lins-MacBook-Pro:httpbin linsun$ curl -I http://169.60.77.242/header
HTTP/1.1 403 Forbidden
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Connection: Keep-Alive
Content-Length: 3369

Lins-MacBook-Pro:httpbin linsun$ curl -I http://169.60.77.242/heade
HTTP/1.1 403 Forbidden
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Connection: Keep-Alive
Content-Length: 3369

not sure why it didn't work with /headers but all other paths have been getting 403 except /headers and /status.

**Comment by linsun** [comment]
Upon further investigation, it appears the deny route rule isn't in pilot's route config for the httpbin's side car:  `curl istio-pilot:8080/v1/routes/http_proxy/istio-proxy/sidecar~172.30.169.83~172.30.169.83~ `. (thanks to @ijsnellf 's help!)

Also, looking at the code, it seems we calculated the Fault in route.buildHTTPRoute() however it is not being consumed anywhere from what I can tell.
