### ISSUE TITLE
Issue with _docs/setup/kubernetes/quick-start.md

### ISSUE THREAD

**Issue by tjquinno** [istio/istio.github.io#676]
The page should clarify whether istio 0.2 itself requires k8s RBAC and, if not, also describe how to install 0.2 without RBAC (or link to a page with such information). There is ambiguous and seemingly conflicting information around.

First, the page states:

> The following instructions require you have access to a Kubernetes 1.7.4 or newer cluster with RBAC (Role-Based Access Control) enabled.

This does not categorically say that istio 0.2 _itself_ requires RBAC, only that the _instructions_ on the page require RBAC. There are no instructions and no links to other pages for installing istio 0.2 _without_ RBAC, which _suggests_ but does not clearly declare that istio requires RBAC.

Second, the discussion on the 0.1 version of the [installation page](https://www.google.com/url?q=https%3A%2F%2Fistio.io%2Fv-0.1%2Fdocs%2Ftasks%2Finstalling-istio.html&sa=D&sntz=1&usg=AFQjCNGWWYoDrrxLV4LRvAbCMnXzZhKPTQ) about checking for RBAC and installing istio with or without it is absent from the 0.2 Quick Start page. It seems as if it would have been a conscious choice to remove that discussion, further implying that istio 0.2 requires RBAC.

Third, the istio installation files for 0.2.7 do not contain any non-RBAC variants.

Fourth, the discussion of the new 0.2.7 Helm chart [here](https://www.google.com/url?q=https%3A%2F%2Fkubeapps.com%2Fcharts%2Fincubator%2Fistio&sa=D&sntz=1&usg=AFQjCNEVH_m8zSOZXyMiA_Hty_aw9B2akw) states that RBAC is optional (and in fact says that the default is for the chart to install istio _without_ RBAC) which seems to contradict the istio pages.

I have not had a change to dig into the new Helm chart to see exactly what's going on in there wrt RBAC, but it seems as if 

- the  istio 0.2 pages should be clarified about whether istio itself requires k8s RBAC,
- if istio 0.2 _does not_ require RBAC it needs to document the non-RBAC case and provide non-RBAC yaml files in the installation, and
- if istio _does_ require RBAC now then the new Helm chart and its pages need to be reconciled with that.

**Comment by tjquinno** [comment]
BTW, Costin just updated the Google groups [thread](https://groups.google.com/d/msg/istio-users/yF332POxo7s/SkwQyJB2BQAJ) on this topic, stating that istio does _not_ require RBAC.

In that case the istio 0.2 page is quite misleading as written re: RBAC.

**Comment by tjquinno** [comment]
And, Lin has responded further on the Google groups thread, if I may paraphrase arguing that maybe RBAC should be stated as a requirement, if only because all testing has been done on clusters with RBAC.

Clarity on the 0.2 page one way or the other would be most welcome!

**Comment by ldemailly** [comment]
Istio trying to encourage best practices, I don't think we need to document how to install without RBAC
