### ISSUE TITLE
need to specify namespace in istioctl commands in _docs/tasks/traffic-management/request-routing.md

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio.github.io#693]
I'm using version 0.2.9. I'm getting error when I don't specify default namespace.

`~/istio-0.2.9$ istioctl create -f samples/bookinfo/kube/route-rule-all-v1.yaml`
`Error: an empty namespace may not be set during creation`

Maybe this is a bug of istioctl?

**Comment by frankbu** [comment]
@jasonwzm I think this has been fixed: https://github.com/istio/old_pilot_repo/pull/1499
Please try again using the latest istio (0.3.0).

btw, using `kubectl create -f ...` instead of `istioctl` should also work in 0.2.9.

**Comment by christian-posta** [comment]
istioctl does some validation of the resources before submitting it, doesn't it? are we to ignore istioctl for creating resources? this need to specify namespace exists for 0.4 as well.

**Comment by ldemailly** [comment]
rules should be created with istioctl indeed to get validation 

the current instructions and code should be correct afaik

**Comment by christian-posta** [comment]
So, following up RE namespace issues with istioctl: 

https://github.com/istio/istio/issues/2486
