### ISSUE TITLE
k8s automatic injection docs need update

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#697]
https://istio.io/docs/reference/commands/istioctl.html#istioctl-kube-inject

https://github.com/istio/pilot/blob/master/doc/proxy-injection.md

incorrectly says it's not supported

https://github.com/istio/pilot/issues/335#issuecomment-341160462

**Comment by ayj** [comment]
https://istio.io/docs/reference/commands/istioctl.html#istioctl dcs for kube-inject have been updated to reflect that automatic injection is supported. https://github.com/istio/istio/pull/3249 removes the original stale docs for kube-inject.
