### ISSUE TITLE
Ingress tutorial - route rules are not working 

### ISSUE THREAD

**Issue by wstrange** [istio/istio.github.io#702]
Following the ingress tutorial at . https://istio.io/docs/tasks/traffic-management/ingress.html 

minikube 0.22.3, running Kube 1.8.0 , istio-0.2.10/

Kube started with: 

minikube start \
--extra-config=apiserver.Authorization.Mode=RBAC \
--extra-config=apiserver.Admission.PluginNames="Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,GenericAdmissionWebhook,ResourceQuota"

1) minor problem with namespaces in the example. I had to add -n default to the istioctl commands. 

2) The ingress works OK (I get routed to the page), but the deny rule does not work.. All pages can be accessed, even non /status ones

The side car looks like it was injected OK into the httpbin pod.

**Comment by wstrange** [comment]
Do you want me to refile this under  https://github.com/istio/issues?

**Comment by rshriram** [comment]
Fixed by #796. Fault injection does not work in ingress.
