### ISSUE TITLE
Dashboard contents in service graph document.

### ISSUE THREAD

**Issue by fleeto** [istio/istio.github.io#712]
> This task shows you how to setup and use the Istio Dashboard to monitor mesh traffic. As part of this task, you will install the Grafana Istio addon and use the web-based interface for viewing service mesh traffic data.

https://github.com/istio/istio.github.io/blob/master/_docs/tasks/telemetry/servicegraph.md

https://istio.io/docs/tasks/telemetry/servicegraph.html

**Comment by skyao** [comment]
When we are translating this chapter, we find it :)

**Comment by ldemailly** [comment]
I don't understand what the issue is about ? can you clarify what is needed / missing / what is the issue ?

**Comment by fleeto** [comment]
The first paragraph of the page of **Generating a Service Graph**:

This task shows you how to **setup and use the Istio Dashboard** to monitor mesh traffic. As part of this task, you will **install the Grafana Istio addon** and use the web-based interface for viewing service mesh traffic data.

I think it should be replaced with something about `Service Graph`.

**Comment by skyao** [comment]
@ldemailly any update for this issue?

**Comment by ldemailly** [comment]
sorry, I  missed the previous update but I get your point, you could submit a pr but otherwise maybe @douglas-reid can reformulate/clarify the text

**Comment by ldemailly** [comment]
Thanks for the fix @fleeto !
