### ISSUE TITLE
remove jenkins from istio.github.io hooks/checks

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#720]
I've setup circleci rake test (#719) as a replacement for the broken jenkins to check for bad html and links

it happens to be a lot faster thanks to caching too

can you remove the jenkins from the hooks ? I didn't see where that setting is ?

thanks!

**Comment by sebastienvas** [comment]
jenkins is using a webhook at the org level. I deleted the jobs in there. Thanks!

**Comment by ldemailly** [comment]
thanks!
