### ISSUE TITLE
Missing Glossary Entry

### ISSUE THREAD

**Issue by gnirodi** [istio/istio.github.io#761]
Could someone please arrange to have this glossary reconciled with https://goo.gl/An5Qg2
I suspect this glossary should be authoritative over that doc. But in that case, the status of that doc needs to be updated and that doc should have a pointer to this page as being authoritative.

**Comment by ldemailly** [comment]
You can make PRs you know :-)

**Comment by geeknoid** [comment]
@gnirodi Please add any missing word from Google docs into the istio.io glossary and then delete the Google doc so we don't risk going out of sync anymore. istio.io is the authoritative place for this stuff.
Thanks.

**Comment by geeknoid** [comment]
We're OK on this front.
