### ISSUE TITLE
Links in site header have to be tapped twice to work on touch devices 

### ISSUE THREAD

**Issue by ilyasotkov** [istio/istio.github.io#777]
As I was browsing the site on my iPad, I noticed that links in the header (About, Docs, Help, etc.) need to be tapped twice to work. The first tap adds an underlining, but doesn’t activate the link.

**Comment by geeknoid** [comment]
I just tried this on Mac+Chrome, Mac+Safari, Windows+Edge, Windows+Chrome, Windows+IE, Android+Chrome and they all work fine: a single tap gets you to where you're doing.

iOS+Safari though requires a double-tap. And it seems to only affect the links in the top nav, other links on the site require single taps as expected. I haven't got a clue what's going on.

**Comment by ilyasotkov** [comment]
https://github.com/istio/istio.github.io/blob/master/_sass/modules/_nav.scss

**Comment by geeknoid** [comment]
Thanks for the pointer, it's certainly related to that. The article mentions it only seems to affect use of the visibility of display properties, but our CSS doesn't use those. So there's obviously some additional bit of interaction going on. But I've got something to go on...

**Comment by ilyasotkov** [comment]
Just got around to serve the website locally, can confirm it's that line

```scss
```

**Comment by geeknoid** [comment]
Works as of PR #826
