### ISSUE TITLE
Add an "In the News" section to istio.io

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#786]
We should add a page to istio.io which tracks Istio news coverage. 

If we can find someone that is willing to maintain the content on this page, I'd be happy to help set it up.

@louiscryan @smawson @rshriram @linsun @thisisnotapril

**Comment by linsun** [comment]
I'd be happy to help maintain it, assuming people is willing to keep me posted on things.

**Comment by geeknoid** [comment]
My plan is to leverage the "About" link in the top nav to bring up the existing About page with a bunch of links in the left sidebar. Links would include "In the news", a link to get press material (artwork mainly), maybe the release roadmap, etc.

**Comment by linsun** [comment]
I think that works.  Having release roadmap moved there would be good.  I can never find our roadmap without a google search.

**Comment by zinuga** [comment]
link to release notes is a good idea from here.
