### ISSUE TITLE
Issue with _docs/setup/consul/quick-start.md - istioctl context-create fails

### ISSUE THREAD

**Issue by hervenicol** [istio/istio.github.io#791]
"`istioctl context-create --api-server http://localhost:8080`" creates config in `~/.kube/config`, while we want to update `install/consul/kubeconfig`

On top of that "`localhost:8080`" is ok from the host, but not from inside the container.

So, this command seems to work better:
`istioctl context-create --api-server http://istio-apiserver:8080 -c install/consul/kubeconfig`

However, it won't work after a first "`docker-compose up`" because it has created the `kubeconfig` mountpoint as a directory.
In the end the complete `istioctl context-create` step looks like this:
```
rmdir install/consul/kubeconfig
docker rm consul_pilot_1
istioctl context-create --api-server http://istio-apiserver:8080 -c install/consul/kubeconfig
docker-compose -f install/consul/istio.yaml up -d
```

**Comment by steffengy** [comment]
That only seems to be a fault with the 0.3 release:

In the current master that already exists: https://github.com/istio/istio/blob/master/install/consul/kubeconfig

(That more around consul seems broken is another story...)

**Comment by GregHanson** [comment]
File was somehow not included in the release tar after the mono repo switch.  resolved by https://github.com/istio/istio/pull/1998 .  tar will be updated when next release is cut and the getIstio download script pointed to the new version

**Comment by GregHanson** [comment]
just copy https://github.com/istio/istio/tree/master/install/consul/kubeconfig into your install/consul directory
