### ISSUE TITLE
Add full blog post to RSS feed

### ISSUE THREAD

**Issue by marcjoha** [istio/istio.github.io#827]
The blog feed only contains the post description, typically a one-liner. For those of us that read blogs through an RSS reader, can the full post be included please?

**Comment by christian-posta** [comment]
So I took a look at adding this with https://github.com/jekyll/jekyll-feed but there are some misaligned dependencies with github-pages (dependency on `typhoeus` 0.7 when jekyill-feed needs `typhoeus` 1.3). Happy to have any suggestions.

**Comment by marcjoha** [comment]
I'm not familiar with jekyll and jekyll-feed, but a cursory look leads me to believe it's already enabled? Config file here https://github.com/istio/istio.github.io/blob/master/feed.xml.

Apache Beam, also running on jekyll-feed, is just outputting a different field into the description tag: https://github.com/apache/beam-site/blob/asf-site/src/feed.xml#L15

**Comment by christian-posta** [comment]
Yah, i must have missed that.

Can you take a look here: http://istio.io/feed.xml

**Comment by marcjoha** [comment]
Yeah the feed is there, it's just that the <description> tag only has the... description. I want the full article.

Beam is dumping the full content into the <description> tag, and this seems to do the trick.

**Comment by geeknoid** [comment]
Dumping the full content of a blog post into an RSS description element doesn't seem right. I'm no RSS expert, but I just checked several sources online and they all indicate "description" is for a synopsis. Pouring a whole HTML document in there doesn't seem appropriate.

Is there a de facto standard where people are doing this and readers support that?

**Comment by geeknoid** [comment]
Here's a nice post explaining this stuff: https://developer.mozilla.org/en-US/docs/Archive/RSS/Article/Why_RSS_Content_Module_is_Popular_-_Including_HTML_Contents
