### ISSUE TITLE
Comparison between istio and similar software

### ISSUE THREAD

**Issue by christophetd** [istio/istio.github.io#854]
When I started looking into istio / linkerd / envoy it was unclear to me what were the differences between those tools, and how they relate together. I think it would be a great idea to have a section `istio vs other software` under the [What is istio](https://istio.io/docs/concepts/what-is-istio/) section. 

Quite a lot of other projects are doing that (e.g. [Envoy](https://www.envoyproxy.io/docs/envoy/latest/intro/comparison), [Nomad](https://www.nomadproject.io/intro/vs/index.html), [Ambassador](https://www.getambassador.io/about/why-ambassador#alternatives-to-ambassador), etc.), and I think it would help new users get a quick grasp at how istio compares to "similar" software.

Let me know what you think about that - I'd gladly submit a PR if you feel that's useful.

**Comment by christian-posta** [comment]
I think that would be great! Would love to see a PR -- I can contribute to that as well.

**Comment by christophetd** [comment]
Great! I'll send out a proposal PR in the next few days (worst case next week).

**Comment by linsun** [comment]
hey @christophetd I agree this can be useful if it is neutral and unbiased.  If it is more of personal opinion or viewpoint, it'd be best if it is hosted on some other sites imho.  If that still sounds interesting, look forward to seeing what you come up with!

**Comment by gyliu513** [comment]
Thanks @christophetd for the initiative, +1000 for this! One minor comment is shall we also add `Spring Cloud` as a comparison?

**Comment by christophetd** [comment]
> I agree this can be useful if it is neutral and unbiased

Definitely. Biased comparisons on a product's website only lowers its credibility.

**Comment by christophetd** [comment]
PR: #865

**Comment by geeknoid** [comment]
Lets leave this to the outside world.
