### ISSUE TITLE
Issue with _docs/concepts/traffic-management/img/pilot/ServiceModel_Versions.svg

### ISSUE THREAD

**Issue by patricekrakow** [istio/istio.github.io#869]
Looking at the image https://istio.io/docs/concepts/traffic-management/img/pilot/ServiceModel_Versions.svg, I think that the box at the bottom right currently labelled << SvcB >> should be labelled << SvcB' >> (B prime) as it should be a different variant of the service << serviceB.example.com >>.

This B prime correction would be in line with the drawing https://istio.io/docs/concepts/traffic-management/img/pilot/TrafficManagementOverview.svg.

**Comment by ldemailly** [comment]
if you have an svg editor, feel free to edit the picture/submit a PR - thanks!

**Comment by patricekrakow** [comment]
I would like to, but I am a bit new to SVG too ;-)
I have installed Inkscape, and it looks like the text "svcB" is not editable, so I would have to re-create it, but I do not know what was the font, nor the size...
Are those drawings done directly in SVG, or are they done with another tool and then exported in SVG?
-- thanks for your help and sorry for all these questions!

**Comment by ldemailly** [comment]
@geeknoid do you know where we have the source of those drawings ? maybe somewhere on the community drive ?

**Comment by rshriram** [comment]
It was made using AffinityDesigner .. and stored as svg.

**Comment by patricekrakow** [comment]
@rshriram I have installed the trial version (only 10 days) of Affinity Designer, and was about to ask you about the original .afdesign files...
But, I have also found the drawing in a editable mode within a presentations on the team drive ;-) So, maybe I can modify the drawing from a new single slide presentation (to be copied to the team drive) and also commit a text file into the repo giving a link to this slide, to ease future editing of the drawings... What do you think? Should I have a try?

**Comment by patricekrakow** [comment]
I found all the drawing on the community drive: Istio Community > Working Groups > Diagrams > ServiceModel_Versions (Google Drawings) ;-)
I will try to make PR with a modified copy as I can't modify the original one...

**Comment by patricekrakow** [comment]
Voila ;-) I have made my very first PR #876. It is literally to change a comma - adding an apostrophe to be exact- but, I need to start somewhere ;-)

**Comment by ldemailly** [comment]
congrats, your fix is live on https://istio.io/docs/concepts/traffic-management/request-routing.html

thx!
