### ISSUE TITLE
Add task for circuit breaking

### ISSUE THREAD

**Issue by christian-posta** [istio/istio.github.io#872]
We see lots of questions about circuit breaking with istio -- would be good to document circuit breaking as a task.

**Comment by kameshsampath** [comment]
@christian-posta I would like to see a similar example with two deployments v1 and v2 with no routing rules, then add Destination Policy with CB - what I see as of 0.4.0 the Circuit is not tripping.

**Comment by GnawNom** [comment]
@kameshsampath 

I think you might be running into this

> Note: Destination policies will be applied only if the corresponding tagged instances are explicitly routed to. In other words, for every destination policy defined, at least one route rule must refer to the service version indicated in the destination policy.

(from https://istio.io/docs/reference/config/traffic-rules/destination-policies.html)

**Comment by kameshsampath** [comment]
@GnawNom - you are right i had issue because of no route rules , hence thought call it out in the example

**Comment by geeknoid** [comment]
There is now a task for circuit-breaking.
