### ISSUE TITLE
Add a task for JWT-Auth filter

### ISSUE THREAD

**Issue by kameshsampath** [istio/istio.github.io#877]
It will be great to add a task for adding Istio JWT-Auth filer example to the set of Istio examples. I have one example https://git.io/vN02l, I can contribute a PR

**Comment by qiwzhang** [comment]
@kameshsampath Just FYI.   I am in the middle of refactory JWT-auth code at https://github.com/istio/proxy/tree/master/src/envoy/auth.

The config format is changed a little bit.  Please watch the relevant PR in coming week.

**Comment by qiwzhang** [comment]
For Istio,  it is not recommended that users adding JWT-auth filter directly.    Users are supposed to use Istio config define here https://github.com/istio/api/blob/master/mixer/v1/config/client/auth.proto
and use "kubectrl apply" to apply it.

Here is the config example:
https://github.com/manlinl/mgm/blob/master/bookinfo/auth_config.yaml

**Comment by kameshsampath** [comment]
@qiwzhang I am with you on this meaning to say we configure JWT-Auth via EndUserAuthenticationSpec,  translate the discussion we had in https://groups.google.com/d/topic/istio-security/46pn4t8aWes/discussion , we an wait until the refactoring is done.  Ideally it will be great to show a task to the user with it as we had a really good discussion there. WDYT? If you see my example i did not patch/rebuild envoy, I did refactor my example based on the discussion in Istio Security groups thread

**Comment by wattli** [comment]
Refer here https://github.com/istio/istio.github.io/issues/1019
