### ISSUE TITLE
Issue with _docs/reference/config/traffic-rules/routing-rules.md

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#883]
- ./_site/docs/reference/config/traffic-rules/routing-rules.html
  *  External link https://www.envoyproxy.io/docs/envoy/latest/api-v2/rds.proto.html#routeaction-requestmirrorpolicy failed: 404 No error

**Comment by christian-posta** [comment]
Will update this asap. Thx

**Comment by ldemailly** [comment]
@kyessenov matt mentioned you changed v2 on envoy side, what's the new link/can you update our doc ? and think about how we can automatically keep those in sync maybe ?

**Comment by christian-posta** [comment]
I'll update to this:

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#route-routeaction-requestmirrorpolicy

Also relevant:

https://github.com/envoyproxy/data-plane-api/blob/3efeaf53c64c0f5edd2f4ea5d38ae91aba6ded5d/envoy/api/v2/route/route.proto#L420
