### ISSUE TITLE
Update automatic sidecar injection prerequisites for k8s 1.9 (minikube)

### ISSUE THREAD

**Issue by ayj** [istio/istio.github.io#885]
https://istio.io/docs/setup/kubernetes/sidecar-injection.html#prerequisites for minikube need to be updated for k8s 1.9 to enable support for mutating webhooks.

```bash
$ kubectl api-versions | grep admissionregistration.k8s.io/v1beta1
admissionregistration.k8s.io/v1beta1
```

See https://archive.istio.io/v0.4/docs/setup/kubernetes/sidecar-injection#prerequisites for previous 0.4.0 doc version.

**Comment by cmluciano** [comment]
@ayj For https://istio.io/docs/setup/kubernetes/sidecar-injection.html#installing-the-webhook 

Should `./install/kubernetes/webhook-create-signed-cert.sh` be bundled in the release?

**Comment by ayj** [comment]
Yes, see https://github.com/istio/istio/issues/3030

**Comment by gyliu513** [comment]
@ayj one question, I found that the api aggregator of `admissionregistration.k8s.io/v1beta1` was enabled by default in Kubernetes 1.9.x, why do we still file this issue?

**Comment by moderation** [comment]
The quick start documentation has been updated to refer to 0.5 but is still referring to `istio-initializer.yaml` files that don't existing in 0.5 - https://istio.io/docs/setup/kubernetes/quick-start.html

**Comment by ayj** [comment]
@gyliu513, older versions of minikube don't support 1.9 out of the box. See https://github.com/istio/istio/pull/2883 for updated minikube setup steps.

**Comment by ayj** [comment]
@moderation, this should be fixed by https://github.com/istio/istio.github.io/pull/909
