### ISSUE TITLE
Update automatic sidecar injection prerequisites for k8s 1.9 (IBM CCS) 

### ISSUE THREAD

**Issue by ayj** [istio/istio.github.io#887]
https://istio.io/docs/setup/kubernetes/sidecar-injection.html#prerequisites for IBM CCS need to be updated for k8s 1.9 to enable support for mutating webhooks.

```bash
$ kubectl api-versions | grep admissionregistration.k8s.io/v1beta1
admissionregistration.k8s.io/v1beta1
```

See https://archive.istio.io/v0.4/docs/setup/kubernetes/sidecar-injection#prerequisites for previous 0.4.0 doc version.

**Comment by linsun** [comment]
Think this can be closed via #1072
