### ISSUE TITLE
Webpage load issue (chrome reports unsafe scripts)

### ISSUE THREAD

**Issue by rshriram** [istio/istio.github.io#9]
```Mixed Content: The page at 'https://istio.io/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://istio.io/js/jquery.collapsible.js?_=1491483091322'. This request has been blocked; the content must be served over HTTPS.```

**Comment by geeknoid** [comment]
Is this fixed now?

**Comment by esnible** [comment]
I had not tried with Chrome before.  I tried today and only got one security error from Chrome:

```
Refused to load the image 'https://istio.io/favicon.ico' because it violates the following Content Security Policy directive: "img-src data:".
```

I also found 10 broken links; I don't know if you want these here or in another Issue.
https://istio.io/docs/tasks/tbd.html
https://istio.io/docs/concepts/$/img/arch.svg
https://istio.io/favicons/android-chrome-192x192.png
https://istio.io/docs/tutorials/TBD.html
https://istio.io/docs/reference/attributes.html
https://istio.io/docs/concepts/attributes.md
https://istio.io/docs/concepts/TBD.html
https://istio.io/docs/tasks/...
https://istio.io/docs/samples/istio.VERSION
https://istio.io/docs/reference/attributes.md

**Comment by davetropeano** [comment]
^^^ re: violating the img-src: data policy

The content security policy needs to be updated. Add to the header:

`Content-Security-Policy: allow 'self'; img-src data: <<INSERT DOMAIN NAME>>`

**Comment by geeknoid** [comment]
Dave, where would I insert such a header?

**Comment by geeknoid** [comment]
I fixed the fixable broken links. A couple of them are part of example URLs, so they are intentionally broken.

**Comment by davetropeano** [comment]
@geeknoid I think it goes in `_layouts/base.html` as a `meta` tag. 

See http://qszhuan.github.io/technology/2015/08/12/add_csp_to_github_blog

**Comment by rshriram** [comment]
I think this bug is no longer valid. Chrome does not report unsafe scripts anymore!
