### ISSUE TITLE
Issue with _docs/setup/kubernetes/quick-start-gke-dm.md

### ISSUE THREAD

**Issue by patricekrakow** [istio/istio.github.io#900]
I am currently reviewing the page "Quick Start with Google Kubernetes Engine" while I am experimenting it...

1/ I am again fixing some easy typos ;-)
2/ But, I have also noticed that "deploy/istio-initializer" is not part of my installation. Has it been removed? May I update the documentation accordingly in my branch? Or do I have an issue with installation?

**Comment by geeknoid** [comment]
@salrashid123 Mind taking a look?

**Comment by salrashid123** [comment]
@patricekrakow 
Thanks.  LMK if you want to submit the PR.  I already have one pending to fix the alpha cluster requirement in the docs as well as update it for ```0.5.0``` release next week.

If you're already inflight with the PR, i'll just resync with yours.

**Comment by ldemailly** [comment]
ps: use 0.5.1 if possible or make it easy to switch to 0.5.1 as it's coming early next week
(and ditto for 0.6 in a couple of weeks)

**Comment by salrashid123** [comment]
@selmanj 

hes got a PR pending for ```0.5.0```  so he can alter for ```0.5.1``` as needed

**Comment by salrashid123** [comment]
@selmanj  We can close this out (we've updated the docs (i verified it last week)

the latest DM is using  [0.6.0](https://github.com/istio/istio/blob/master/install/gcp/deployment_manager/istio-cluster.jinja.schema#L46)
