### ISSUE TITLE
BookInfo Sample docs need update re: ISTIO_MANAGER_ADDRESS

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.github.io#91]
Running through a fresh install, attempting to recreate the sample app.  Get the following:

```shell
$ kubectl apply -f <(istioctl kube-inject -f bookinfo.yaml)
Error: manager address environment variable is not set, please set ISTIO_MANAGER_ADDRESS to the location and port of you Istio manager
error: no objects passed to apply
```

1. We need to add the setting of environment variables to the Task
1. The error message should read "port of you*r* Istio manager" (instead of "port of you Istio manager").

**Comment by ldemailly** [comment]
fixed by https://github.com/istio/manager/pull/669
