### ISSUE TITLE
add section for performance and scalability

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#911]

**Comment by cmluciano** [comment]
Do we want a dedicated page that shows things like https://github.com/istio/istio/wiki/Istio-Performance-oriented-setup-FAQ#automatic-proxy-injection and fortio.istio.io ?

**Comment by ldemailly** [comment]
yes it would present in a operator consumable way the perf related setup and tweaks,
inline (maybe iframe!) the key results from https://fortio.istio.io as well as IBM's setup
with explanations on how to interpret the results as well as key take aways from the Perf&Scale WG

**Comment by ldemailly** [comment]
will have a link to http://ibmcloud-perf.istio.io/regpatrol/ as well
