### ISSUE TITLE
(cosmetic) new `command line example` is pink, not matching blockquote

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#913]
the new `command line example` style, without border also appears lighter/pink color and is a bit hard to make out on a white background:

![screen shot 2018-01-31 at 4 08 28 pm](https://user-images.githubusercontent.com/3664595/35654248-1c2dfe8a-06a1-11e8-9f96-08abdc2da669.png)

it should be the same color as in a blocquote (```):

![screen shot 2018-01-31 at 4 10 58 pm](https://user-images.githubusercontent.com/3664595/35654321-65f1af8a-06a1-11e8-918d-65d62c7f0c42.png)

`cluster-name` vs `export KUBECONFIG` above

**Comment by ldemailly** [comment]
if you point me to the css I can make the change if you want

**Comment by geeknoid** [comment]
I think that comes from syntax.css. But I'd have to track it down...

**Comment by ldemailly** [comment]
fixed in #924
