### ISSUE TITLE
The docs referenced in the 0.5 version are not open to the public

### ISSUE THREAD

**Issue by ohellman** [istio/istio.github.io#929]
The links for "learn more" under Open Policy Agent and RBAC links to a google document that is not open to the public. 

(https://docs.google.com/document/d/1U2XFmah7tYdmC5lWkk3D43VMAAQ0xkBatKmohf90ICA/edit#heading=h.fmlgl8m03gfy) and (https://docs.google.com/document/d/1dKXUEOxrj4TWZKrW7fx_A-nrOdVD4tYolpjgT8DYBTY/edit#)

https://istio.io/about/notes/0.5.html

**Comment by geeknoid** [comment]
This is normal for Istio design documents. You can request access and get in without any requirement.

Note that there is currently an outage in the underlying infrastructure which prevents us from granting access to anyone asking. Hopefully, this issue will be resolve in the next few days. Everyone in the queue will be allowed in at that time.
