### ISSUE TITLE
Testing Istio mutual TLS authentication - cURL

### ISSUE THREAD

**Issue by srinandan** [istio/istio.github.io#933]
The instruction on the page https://istio.io/docs/tasks/security/mutual-tls.html ask that you test mTLs using cURL. cURL is not installed on any of pods. You also cannot install it (unless I'm missing something). Maybe we need a different set of instructions or add cURL into the bookinfo app.

**Comment by ldemailly** [comment]
curl is present on the _debug images you get when you `istioctl kube-inject --debug=true`

we probably need to add that reminder now that the default changed

**Comment by wattli** [comment]
It's already done, see step 4 of this page.
