### ISSUE TITLE
GKE Documentation incompatible with automatic sidecar injection

### ISSUE THREAD

**Issue by sdake** [istio/istio.github.io#939]
https://istio.io/docs/setup/kubernetes/quick-start-gke-dm.html

Has no mention of `whitelisting` for Kubernetes 1.9.2 which I'm not sure how to do.  The docs as is crater badly when bookinfo is deployed with the sidecar.

**Comment by ldemailly** [comment]
a pr (https://github.com/istio/istio/pull/2997) is waiting to make it work, one of the issue is it's still using istio 0.3 yet fetches files from master on github

**Comment by sdake** [comment]
@ldemailly sure - aware of that PR (but thanks for the pointer, as I couldn't find it), however, the docs also need a rev after that merges.

**Comment by ldemailly** [comment]
totally agree the doc needs update too

**Comment by ayj** [comment]
GKE 1.9 should be GA now, so no white listing is required.

cc @salrashid123 @selmanj for GKE doc updates

**Comment by salrashid123** [comment]
thanks.  I'll submit the doc bug PR over the weekend

@selmanj   will remove the ```enableKubernetesAlpha: true``` setting in the DM template thats there now

**Comment by sdake** [comment]
this looks resolved.
