### ISSUE TITLE
Missing webhook-create-signed-cert.sh

### ISSUE THREAD

**Issue by jsenon** [istio/istio.github.io#959]
Script `install/kubernetes/webhook-create-signed-cert.sh` is missing on archive when perform `curl -L https://git.io/getLatestIstio | sh -` 

Plateform:
`Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`

**Comment by ldemailly** [comment]
this is fixed in master / next release afaik

**Comment by jsenon** [comment]
Do I have to update docs according to your comment?

**Comment by ldemailly** [comment]
@ajy ^

**Comment by ayj** [comment]
fixed by https://github.com/istio/istio.github.io/pull/979
