### ISSUE TITLE
Finish setting up Istio's custom search engine

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#96]
There are three outstanding tasks around Istio's use of Google's Custom Search Engine:

- We need to register our search engine as being for a non-profit. This will let us remove ads from the returned search results.

- We need to enable search engine analytics so we can understand what people are looking for on the Istio site.

- We need to configure the search engine with various options such as auto-complete text, which improves the end-user's experience.

I've added you (Varun) as an admin of the search engine. Visit google.com/cse for the control panel.

**Comment by LisaFC** [comment]
Here's the instructions for labelling the search engine as non-profit/ad-free: https://support.google.com/customsearch/answer/70354?hl=en

**Comment by geeknoid** [comment]
I went ahead and disabled ads.

We'll be getting contacted by Google legal people to confirm our non-profit status.

**Comment by ldemailly** [comment]
I think this is settled/working fine ?
