### ISSUE TITLE
Add a link to [download istio] to istio.io front page

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.github.io#962]
On the istio.io front page, there is no "Download" link, or a link that points to istio releases page.

One has to scroll down all the way to "Get Started"  --> "Setup"  and then select "Install" to be able read about what to download.

**Comment by geeknoid** [comment]
Should it be a link to https://github.com/istio/istio/releases?

**Comment by ldemailly** [comment]
Fixed in #965 ! nice !
