### ISSUE TITLE
Need to refer to subsection in any of our doc easily as a url

### ISSUE THREAD

**Issue by linsun** [istio/istio.github.io#977]
i noticed on istio.io site, i can’t click on a subsection to point to a url, for example, installation steps in k8s quick start:  https://istio.io/docs/setup/kubernetes/quick-start.html

 i would like to click on “installation steps” section in this doc, and give people the link pointing to that section.

Per @geeknoid - this can only be done using the TOC on the right side but not from main text today.

**Comment by geeknoid** [comment]
Do you like how this site does it?

https://getbootstrap.com/docs/4.0/getting-started/introduction

When you hover on a heading, it shows a hash sign to click on, which gives you the URL of that particular heading.

**Comment by linsun** [comment]
@geeknoid Yes that looks great!  I personally prefer a hyperlink icon vs a # icon, but either one is okay.

**Comment by ldemailly** [comment]
what github does with markdown is nice sections is nice (mouse over showing link)

![screen shot 2018-02-12 at 11 52 35 am](https://user-images.githubusercontent.com/3664595/36116480-4699aba8-0feb-11e8-92ef-7118df1317a1.png)

https://github.com/istio/istio/blob/master/README.md#issue-management

**Comment by linsun** [comment]
Yes, that was the icon I was looking for.  thanks @ldemailly
