### ISSUE TITLE
Copy button not responsive in nature 

### ISSUE THREAD

**Issue by neeravarora** [istio/istio.github.io#981]
Copy button seems to be not responsive in nature when the command is huge or when the  user needs to scroll horizontally . It appears to be fixed in a particular position and causes problems while reading the command .
![image](https://user-images.githubusercontent.com/17734724/36136317-d378a0c2-10b5-11e8-861c-ca4c6871aa44.png)

**Comment by geeknoid** [comment]
Ouch.

**Comment by ldemailly** [comment]
related, when the line is long, it's hard to click copy and have it copy, it seems to select the text under it
