### ISSUE TITLE
new light electric blue is poor contrast on white

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#985]
![screen shot 2018-02-13 at 10 47 12 am](https://user-images.githubusercontent.com/3664595/36167744-c38590e4-10ab-11e8-9fe5-244ea438d2f7.png)

**Comment by ldemailly** [comment]
before, which was much better:
![screen shot 2018-02-13 at 10 54 42 am](https://user-images.githubusercontent.com/3664595/36167943-6aa12834-10ac-11e8-9392-6e176f90909f.png)

**Comment by geeknoid** [comment]
Fixed in #1007

-
