### ISSUE TITLE
issue with gear + drop down triangle

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.github.io#996]
I didn't notice until now but 2 things:

<img width="382" alt="screen shot 2018-02-14 at 11 13 51 pm" src="https://user-images.githubusercontent.com/3664595/36244864-f4abc36e-11dc-11e8-9383-b4875f956e91.png">

the triangle looks a bit odd below the gear and the 2 quite tall - and/or need at least to be centered, now it's slightly to the left below the gear

related, I'm concerned I didn't see a preview in the branch PRs and that we lost the right side indication and maybe checkbox of which version a user is currently seeing ?
(firebase preview + copy pasted screen shot would help)

**Comment by geeknoid** [comment]
The triangle sometimes "travels" to below the gear, I haven't tracked down why. On a wide enough display, the triangle is next to the gear.

There are no checkboxes in the older branche for which version is displayed. This only shows up in the 0.5 snapshot and beyond. The logic doesn't exist in the older site snapshots.

**Comment by ldemailly** [comment]
oic it changes at about 1400 pixel wide - I guess it's the responsive design, you can probably make the gear + drop down a single non responsive small block

unrelated / forgot where I mentioned it but it is important if we're switching the main site to pre 0.6:
please sync the 0.5 branch (minus the data/version dir) before pushing - I merged late last night PRs that do apply to 0.5.1

**Comment by geeknoid** [comment]
Please go ahead and cherry pick whatever PRs you'd like to have in the 0.5
archive. They'll get reflected next time archive.istio.io is rebuilt.

**Comment by geeknoid** [comment]
Addressed by #1007
